const fs=require('fs'),path=require('path'),assert=require('assert'),puppeteer=require('puppeteer-core');
(async()=>{const dir=path.resolve(__dirname,'..'),b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--allow-file-access-from-files']}),p=await b.newPage();await p.setViewport({width:1080,height:1920});let errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))external.push(r.url());});await p.goto('file://'+dir+'/index.html');await p.evaluate(()=>document.fonts.ready);await p.waitForFunction(()=>!!window.StoryTimeline,{polling:100});assert.deepEqual(errors,[]);const {plan,ops,reveals,checks}=await p.evaluate(()=>({plan:PLAN,ops:OPERATION_SAMPLES,reveals:REVEAL_SAMPLES,checks:STATE_CHECKS}));fs.mkdirSync(dir+'/snapshots',{recursive:true});const seek=async t=>p.evaluate(t=>{StoryTimeline.seek(t,false);},t);const issues=[];
async function inspect(t,label){await seek(t);const out=await p.evaluate(()=>{const visible=n=>{for(let a=n;a&&a.nodeType===1;a=a.parentElement){const s=getComputedStyle(a);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.8)return false;}return true;};const candidates=[...document.querySelectorAll('.copy,.identity,.name,.body,.footer,.request,.badge,.evidence,.data,.paper,.caption-line')].filter(visible);const overflow=candidates.filter(n=>n.scrollWidth>n.clientWidth+3||n.scrollHeight>n.clientHeight+3).map(n=>({id:n.id,cls:n.className,text:n.textContent,box:[n.clientWidth,n.clientHeight,n.scrollWidth,n.scrollHeight]}));const captions=[...document.querySelectorAll('.caption-line')].filter(visible).map(n=>n.textContent);return {overflow,captions,visibleShots:[...document.querySelectorAll('#srp-stage>.shot')].filter(visible).length};});if(out.overflow.length||out.captions.length>1||out.visibleShots!==1)issues.push({t,label,...out});return out;}
for(let i=0;i<plan.sections.length;i++){const s=plan.sections[i],t=s.start+s.dur-.6;await inspect(t,'section-'+i);await p.screenshot({path:dir+'/snapshots/section-'+String(i).padStart(2,'0')+'.png'});}
const selected=ops.filter(x=>x.job.includes('inspect/reframe')||x.job.includes('transfer')||x.job==='state commit');for(let i=0;i<selected.length;i++){const op=selected[i];for(const [tag,t] of [['before',Math.max(0,op.start-.05)],['mid',(op.start+op.end)/2],['after',op.end+.08]]){if(t>=plan.total)continue;await inspect(t,'op-'+i+'-'+tag);if(op.job.includes('transfer')||op.job.includes('inspect/reframe')&&op.start>=plan.sections[6].start&&op.start<plan.sections[8].start)await p.screenshot({path:dir+'/snapshots/op-'+i+'-'+tag+'.png'});}}
// Content should stay hidden before its first authored reveal, including after jumping backwards.
const revealLeaks=[];for(const r of reveals){if(r.t<.06)continue;await seek(Math.min(plan.total-.05,r.t+.6));await seek(r.t-.04);const leaks=await p.evaluate(id=>{const n=document.getElementById(id);if(!n)return false;for(let a=n;a&&a.nodeType===1;a=a.parentElement){const s=getComputedStyle(a);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.02)return false;}return true;},r.id);if(leaks)revealLeaks.push(r);}
const states=[];for(const c of checks){await seek(c.t);const state=await p.evaluate(()=>({calc:document.querySelector('#calc .identity').textContent,view:document.querySelector('#presenter .identity').textContent,code:document.querySelector('#calc .body').textContent,heading:document.querySelector('.paper-title').textContent,amount:document.querySelector('.paper-amount').textContent}));states.push({...c,state});if(c.check==='both extracted'){assert(state.calc.includes('InvoiceCalculator'));assert(state.view.includes('InvoicePresenter'));}if(c.check==='discount total')assert.equal(state.amount,'90.000 đ');if(c.check==='format isolation'){assert.equal(state.amount,'90.000 đ');assert.equal(state.heading,'PHIẾU\nTHANH TOÁN');}}
for(const i of [12,2,10,7,4,13,0,12]){await inspect(plan.sections[i].start+plan.sections[i].dur-.6,'reverse-'+i);const amount=await p.$eval('.paper-amount',n=>n.textContent);if(i<10)assert.equal(amount,'100.000 đ');if(i>=10)assert.equal(amount,'90.000 đ');}
fs.writeFileSync(dir+'/custom-motion-review.json',JSON.stringify({ops,reveals,states,issues,revealLeaks,errors,external,sections:plan.sections.map(s=>({id:s.id,start:s.start,dur:s.dur})),scope:'Sampled browser states and important native operations; counts are diagnostics, not quality scores.'},null,2));console.log(JSON.stringify({sections:plan.sections.length,operations:ops.length,issues,revealLeaks,errors,external}));await b.close();if(issues.length||revealLeaks.length||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
