const fs=require('fs'),path=require('path'),assert=require('assert/strict'),pp=require('puppeteer-core');
(async()=>{let root=path.resolve(__dirname,'..');const b=await pp.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--allow-file-access-from-files']});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1080,height:1920});await p.goto('file://'+root+'/index.html');await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()))});assert.deepEqual(errors,[]);let r=await p.evaluate(()=>REVIEW);fs.writeFileSync(__dirname+'/timeline.json',JSON.stringify(r,null,2));
async function state(t){await p.evaluate(async t=>{__timelines['pop-collage'].seek(t,true);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))},t);return p.evaluate(()=>({css:[...document.querySelectorAll('#world *')].map(e=>e.style.cssText.replace(/-?\d*\.?\d+/g,n=>String(Math.round(Number(n)*10000)/10000))),captions:[...document.querySelectorAll('.caption')].filter(e=>getComputedStyle(e).visibility==='visible').map(e=>e.textContent)}))}
const times=[0,1.5,3,...r.sections.flatMap(s=>[s.start+.5,s.start+s.dur*.55,s.start+s.dur-.4])],saved=[];const fits=[];
for(let i=0;i<times.length;i++){let s=await state(times[i]);assert(s.captions.length<=1);saved.push(s);await p.screenshot({path:__dirname+'/frame-'+String(i).padStart(2,'0')+'.png'});fits.push(...await p.evaluate(()=>[...document.querySelectorAll('.backplate')].filter(e=>getComputedStyle(e).visibility!=='hidden'&&+getComputedStyle(e).opacity>.8).flatMap(e=>{let a=e.querySelector('.backplate-safe').getBoundingClientRect(),b=e.querySelector('.backplate-copy').getBoundingClientRect();return b.width>a.width+5||b.height>a.height+5?[{text:e.textContent,width:b.width,safe:a.width,height:b.height,safeHeight:a.height}]:[]})));}
fs.writeFileSync(__dirname+'/sampled-styles.json',JSON.stringify(saved,null,2));for(let i=times.length-1;i>=0;i--)assert.deepEqual(await state(times[i]),saved[i],'reverse '+times[i]);
for(let i=1;i<r.sections.length;i++)for(const d of [-1/30,0,1/30]){await state(r.sections[i].start+d);await p.screenshot({path:__dirname+`/join-${i}-${d.toFixed(3)}.png`})}
fs.writeFileSync(__dirname+'/browser-review.json',JSON.stringify({pass:!fits.length,errors,fits,times,reverseSeek:true,audio:await p.$$eval('audio',a=>a.length)},null,2));console.log({duration:r.duration,errors,fits,samples:times.length});assert.equal(fits.length,0,'paper text does not fit');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
