(()=>{
const P=window.PLAN,S=window.SCRIPT,tl=gsap.timeline({paused:true}),stage=document.getElementById('stage'),sections=P.sections;
const samples=[];window.OPERATION_SAMPLES=samples;
const norm=x=>String(x).toLowerCase().normalize('NFC').match(/[\p{L}\p{N}]+/gu)||[];
const sec=id=>sections.find(x=>x.id===id),start=id=>sec(id).start;
function cue(id,phrase){const words=sec(id).words.flatMap(w=>norm(w.w).map(token=>({token,t:w.t0}))),n=norm(phrase),i=words.findIndex((_,i)=>n.every((x,j)=>words[i+j]?.token===x));if(i<0)throw Error('Missing cue '+id+' '+phrase);return words[i].t;}
function el(tag,cls,parent=stage,text){const e=document.createElement(tag);e.className=cls;if(text!=null)e.textContent=text;parent.appendChild(e);return e;}
function box(id,x,y,w,h,color='#fff',parent=stage){const e=el('div','panel',parent);e.id=id;Object.assign(e.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px',background:color,visibility:'hidden',display:'none'});return e;}
function txt(parent,text,x,y,size=36,cls='note',w){const e=el('div',cls,parent,text);Object.assign(e.style,{position:'absolute',left:x+'px',top:y+'px',fontSize:size+'px'});if(w)e.style.width=w+'px';return e;}
function show(e,t,d=.55){tl.set(e,{display:'block',visibility:'visible'},t);tl.fromTo(e,{opacity:0,y:24},{opacity:1,y:0,duration:d,ease:'power2.out',immediateRender:false},t);}
function hide(e,t,d=.3){tl.to(e,{opacity:0,duration:d},t);tl.set(e,{display:'none'},t+d);}
function move(e,vars,t,d=.8,job='recompose'){tl.to(e,{...vars,duration:d,ease:'power2.inOut'},t);samples.push({job,start:t,end:t+d});}
function reveal(e,t,d=.5){tl.fromTo(e,{opacity:0},{opacity:1,duration:d,immediateRender:false},t);}
function concealed(e){gsap.set(e,{opacity:0});return e;}
const changes=new Map();function value(e,text,t){const prev=changes.has(e)?changes.get(e):e.textContent;tl.fromTo(e,{textContent:prev},{textContent:text,duration:0,immediateRender:false},t);changes.set(e,text);}
function lamp(parent,color){const e=el('div','lamp-icon',parent);e.innerHTML=`<svg viewBox="0 0 280 250" xmlns="http://www.w3.org/2000/svg"><path class="beam" d="M182 98 L262 218 L148 218 Z" fill="#feee91" stroke="#2d3436" stroke-width="4" opacity="0"/><g stroke="#2d3436" stroke-width="12" stroke-linecap="round" stroke-linejoin="round"><path d="M54 218 L96 130 L170 49" fill="none"/><path d="M32 219 H110 L123 238 H19 Z" fill="${color}"/><circle cx="96" cy="130" r="12" fill="${color}"/><path d="M151 30 Q182 11 194 43 L222 82 L168 116 Z" fill="${color}"/><path class="bulb" d="M183 107 Q199 133 210 103" fill="#e5e5e5"/></g></svg>`;return e;}
function owner(id,name,color,x,y,w,h){const root=box(id,x,y,w,h,color);root.classList.add('owner');const label=el('div','owner-name',root,name),icon=lamp(root,color==='#a594f9'?'#a594f9':'#ffa239'),field=el('div','field',root),small=el('small','',field,'THUỘC TÍNH'),key=el('span','',field,'on = '),val=el('span','state',field,'False'),method=el('div','method',root);el('small','',method,'PHƯƠNG THỨC');el('span','',method,'turn_on()');gsap.set(field,{left:28,top:h-290,width:w-56,height:120,right:'auto',bottom:'auto'});gsap.set(method,{left:28,top:h-125,width:w-56,height:100,right:'auto',bottom:'auto'});return {root,label,icon,field,val,method};}
function wire(id,d,t,end,color='#2d3436',width=6){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('wire-layer');svg.setAttribute('viewBox','0 0 1080 1920');svg.style.visibility='hidden';svg.style.display='none';stage.appendChild(svg);svg.id=id;const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',d);p.setAttribute('fill','none');p.setAttribute('stroke',color);p.setAttribute('stroke-width',width);p.setAttribute('stroke-linecap','round');p.setAttribute('stroke-linejoin','round');svg.appendChild(p);const length=p.getTotalLength();gsap.set(p,{strokeDasharray:length,strokeDashoffset:length});tl.set(svg,{display:'block',visibility:'visible'},t);tl.to(p,{strokeDashoffset:0,duration:.7,ease:'power2.inOut'},t);if(end)hide(svg,end,.2);samples.push({job:id,start:t,end:t+.7});return svg;}
function token(text,x,y,toX,toY,t,d=.7){const e=el('div','token',stage,text);Object.assign(e.style,{left:x+'px',top:y+'px'});tl.set(e,{visibility:'visible'},t);tl.fromTo(e,{x:0,y:0,opacity:1},{x:toX-x,y:toY-y,duration:d,ease:'power2.inOut',immediateRender:false},t);tl.to(e,{opacity:0,duration:.15},t+d);samples.push({job:'token '+text,start:t,end:t+d});return e;}
function heading(id,text){const e=el('div','title',stage,text);const s=sec(id);show(e,s.start+.05,.4);hide(e,s.start+s.dur-.25,.25);return e;}
const phaseNames=['QUESTION','ÉTAT INITIAL','ÉTAT INITIAL','OBJET','CLASSE','ATTRIBUT','MÉTHODE','CRÉATION','CRÉATION','APPEL','EXÉCUTION','VÉRIFICATION','COMPARAISON','ORGANISATION','RÈGLE'];
const viPhases=['CÂU HỎI','DỮ LIỆU','HÀNH VI','ĐỐI TƯỢNG','LỚP','THUỘC TÍNH','PHƯƠNG THỨC','KHỞI TẠO','KHỞI TẠO','LỜI GỌI','THỰC THI','KIỂM TRA','ĐỐI CHIẾU','CÁCH TỔ CHỨC','GHI NHỚ'];
sections.forEach((s,i)=>{value(document.getElementById('phase'),viPhases[i],s.start);value(document.getElementById('counter'),String(i+1).padStart(2,'0')+' / 15',s.start);});
// 0: dominant poster + semantic icon pair. The answer is still unknown.
const poster=box('poster',64,195,948,650,'#8ce4ff');txt(poster,'OOP',44,34,155,'mono');txt(poster,'Hai chiếc đèn.\nMột lời gọi.',44,250,69,'title',830).style.whiteSpace='pre-line';txt(poster,'Lập trình hướng đối tượng',44,548,31);show(poster,.1);hide(poster,start('scene-1'));
// Override title class inherited hidden/absolute dimensions inside the poster.
const pt=poster.querySelector('.title');Object.assign(pt.style,{visibility:'visible',left:'44px',top:'250px',fontSize:'69px',width:'830px'});
const hookA=box('hook-a',64,885,440,650,'#feee91'),hookB=box('hook-b',560,885,440,650,'#a594f9');lamp(hookA,'#ffa239');lamp(hookB,'#a594f9');txt(hookA,'ĐÈN BÀN',30,34,30,'eyebrow');txt(hookB,'ĐÈN NGỦ',30,34,30,'eyebrow');txt(hookA,'Bật?',30,465,70,'mono');txt(hookB,'?',150,452,110,'mono');show(hookA,.35);show(hookB,cue('intro','đèn còn lại'));hide(hookA,start('scene-1'));hide(hookB,start('scene-1'));
// 1–3: begin with a specimen; state and behavior become owned compartments.
heading('scene-1','Chiếc đèn\ncần nhớ điều gì?');
const concept=owner('concept','CHIẾC ĐÈN','#e5e5e5',64,425,948,1120);gsap.set(concept.root,{borderColor:'transparent',boxShadow:'0px 0px 0px #2d3436'});gsap.set(concept.icon,{left:20,top:230,width:420,height:380});gsap.set(concept.field,{left:485,top:200,right:'auto',bottom:'auto',width:400,height:210,fontSize:47});gsap.set(concept.method,{left:485,top:575,right:'auto',bottom:'auto',width:400,height:195,fontSize:37});concealed(concept.field);concealed(concept.method);show(concept.root,start('scene-1')+.1);reveal(concept.field,cue('scene-1','có trạng thái'));wire('state-link','M435 895 H495 V730 H540 l-14 -10 m14 10 l-14 10',cue('scene-1','dữ liệu'),start('scene-2'));
heading('scene-2','Và có thể\nlàm điều gì?');move(concept.field,{top:140},start('scene-2'),.7,'make room for method');reveal(concept.method,cue('scene-2','có hành vi'));wire('behavior-link','M430 1100 H480 V1125 H532 l-14 -10 m14 10 l-14 10',cue('scene-2','một phương thức'),start('scene-3'));
heading('scene-3','Gom lại thành\nmột đối tượng');const groupAt=cue('scene-3','Gom dữ liệu');move(concept.icon,{left:320,top:150,width:280,height:250},groupAt,.8,'object compartments assemble');move(concept.field,{left:30,top:600,width:415,height:200,fontSize:42},groupAt,.9);move(concept.method,{left:485,top:600,width:415,height:200,fontSize:35},groupAt,.9);move(concept.root,{backgroundColor:'#fff',borderColor:'#2d3436',boxShadow:'12px 12px 0px #2d3436'},cue('scene-3','một đối tượng'),.6,'enclose state and behavior');value(concept.label,'OBJECT · ĐỐI TƯỢNG',cue('scene-3','một đối tượng'));const plus=concealed(txt(concept.root,'+',444,650,50,'mono'));reveal(plus,cue('scene-3','một đối tượng'));hide(concept.root,start('scene-4'));
// 4–6: a class is a specification, with initial-data and behavior definitions.
heading('scene-4','Một mô tả.\nNhiều đối tượng.');
const cls=box('class-spec',64,440,948,1060,'#8ce4ff');txt(cls,'CLASS · LỚP',40,32,28,'eyebrow');const className=txt(cls,'Lamp',40,100,110,'mono');const classCode=txt(cls,'class Lamp:',40,285,48,'mono');const defaults=box('defaults',34,415,872,235,'#feee91',cls);txt(defaults,'TRẠNG THÁI KHI TẠO',25,20,24,'eyebrow');txt(defaults,'on = False',25,84,51,'mono');const methSpec=box('method-spec',34,685,872,235,'#2d3436',cls);txt(methSpec,'HÀNH VI',25,20,24,'eyebrow').style.color='#feee91';txt(methSpec,'turn_on()',25,84,51,'mono').style.color='white';show(cls,cue('scene-4','một lớp'));show(defaults,cue('scene-4','bản thiết kế'));show(methSpec,cue('scene-4','tên Lamp'));
heading('scene-5','Mỗi đối tượng mới\nbắt đầu thế nào?');move(cls,{top:420,height:430},start('scene-5'));move(className,{fontSize:82,top:87},start('scene-5'));move(classCode,{fontSize:36,top:245},start('scene-5'));hide(defaults,start('scene-5'));hide(methSpec,start('scene-5'));
const init=box('constructor',64,905,948,630,'#fff');txt(init,'KHỞI TẠO · PYTHON',35,30,26,'eyebrow');txt(init,'def __init__(self):',35,120,42,'mono');const initLine=concealed(txt(init,'self.on =',65,260,50,'mono'));const falseSlot=box('false-slot',585,245,300,130,'#feee91',init);txt(falseSlot,'False',24,24,53,'mono');const initialTag=concealed(txt(init,'False → đang tắt',35,485,41));show(init,cue('scene-5','mỗi đèn mới'));reveal(initLine,cue('scene-5','thuộc tính on'));show(falseSlot,cue('scene-5','ban đầu là sai'));reveal(initialTag,cue('scene-5','đang tắt'));hide(init,start('scene-6'));
heading('scene-6','Phương thức tác động\nlên đối tượng nào?');move(cls,{top:400,height:275},start('scene-6'));move(className,{fontSize:73,top:75},start('scene-6'));hide(classCode,start('scene-6'));
const methodDetail=box('method-detail',64,725,948,855,'#a594f9');txt(methodDetail,'ĐỊNH NGHĨA · CHƯA CHẠY',35,30,24,'eyebrow');txt(methodDetail,'def turn_on(self):',35,125,43,'mono');const bodyLine=concealed(txt(methodDetail,'self.on = True',65,260,49,'mono'));const receiver=box('receiver-definition',36,535,868,210,'#fff',methodDetail);txt(receiver,'self',25,27,61,'mono');txt(receiver,'Đối tượng nhận lời gọi',250,61,31);show(methodDetail,cue('scene-6','Phương thức bật'));reveal(bodyLine,cue('scene-6','đổi trạng thái'));show(receiver,cue('scene-6','Từ self'));wire('self-definition-link','M325 1070 V1210 H204 V1250 l-10 -14 m10 14 l10 -14',cue('scene-6','chính đối tượng'),start('scene-7'));hide(methodDetail,start('scene-7'));
// 7–8: instantiate along two visible branches, preserving the specification above.
heading('scene-7','Tạo chiếc thứ nhất');move(cls,{top:375,height:325},start('scene-7'));const creationCode=txt(cls,'desk = Lamp()',40,205,42,'mono');concealed(creationCode);reveal(creationCode,cue('scene-7','tạo một đối tượng'));
const desk=owner('desk','desk','#feee91',64,875,440,715),bed=owner('bed','bed','#a594f9',560,875,440,715);
const deskBorn=cue('scene-7','đèn bàn');wire('create-desk','M537 715 V780 H285 V845 l-12 -16 m12 16 l12 -16',deskBorn-.3,start('scene-9'));show(desk.root,deskBorn,.3);tl.fromTo(desk.root,{x:230,y:-110,scale:.55},{x:0,y:0,scale:1,duration:.8,ease:'power2.out',immediateRender:false},deskBorn);samples.push({job:'instantiate desk',start:deskBorn,end:deskBorn+.8});
heading('scene-8','Cùng lớp.\nThêm một đối tượng.');value(creationCode,'bed = Lamp()',cue('scene-8','Tạo tiếp'));const bedBorn=cue('scene-8','đèn ngủ');wire('create-bed','M537 715 V780 H780 V845 l-12 -16 m12 16 l12 -16',bedBorn-.3,start('scene-9'));show(bed.root,bedBorn,.3);tl.fromTo(bed.root,{x:-225,y:-110,scale:.55},{x:0,y:0,scale:1,duration:.8,ease:'power2.out',immediateRender:false},bedBorn);samples.push({job:'instantiate bed',start:bedBorn,end:bedBorn+.8});
// 9: the invocation takes the stage; its two segments target receiver and behavior.
heading('scene-9','Lời gọi đi đến đâu?');hide(cls,start('scene-9'));move(desk.root,{top:950,height:640},start('scene-9'));move(bed.root,{top:950,height:640},start('scene-9'));for(const o of [desk,bed]){move(o.field,{top:350},start('scene-9'));move(o.method,{top:515},start('scene-9'));}const call=box('invocation',64,405,948,345,'#2d3436');txt(call,'LỜI GỌI · PYTHON',32,26,26,'eyebrow').style.color='#feee91';const callDesk=txt(call,'desk',35,115,69,'mono');callDesk.style.color='#feee91';const callMethod=txt(call,'.turn_on()',226,115,69,'mono');callMethod.style.color='white';show(call,cue('scene-9','gọi phương thức'));
wire('resolve-receiver','M255 665 V835 H150 V927 l-12 -16 m12 16 l12 -16',cue('scene-9','Phần trước'),start('scene-10'));const receiverLabel=box('receiver-label',540,785,460,112,'#feee91');txt(receiverLabel,'desk → đèn bàn',20,25,31,'mono');show(receiverLabel,cue('scene-9','Phần trước'));hide(receiverLabel,start('scene-10'));
wire('resolve-method','M800 665 V765 H532 V1520 H516 l16 -12 m-16 12 l16 12',cue('scene-9','phần sau'),start('scene-10'));tl.to(desk.method,{backgroundColor:'#ffa239',color:'#2d3436',duration:.35},cue('scene-9','phần sau'));tl.to(desk.method.querySelector('small'),{color:'#2d3436',duration:.35},cue('scene-9','phần sau'));hide(call,start('scene-10'));
// 10: open only the receiver. Route method → field; commit with the spoken result.
heading('scene-10','Bên trong đèn bàn');move(desk.root,{left:64,top:460,width:650,height:1120},start('scene-10'));move(desk.icon,{left:185,top:110,width:280,height:260},start('scene-10'));move(desk.method,{left:30,right:'auto',top:425,bottom:'auto',width:580,height:170,fontSize:40},start('scene-10'));move(desk.field,{left:30,right:'auto',top:840,bottom:'auto',width:580,height:190,fontSize:54},start('scene-10'));move(bed.root,{left:772,top:1000,width:230,height:580},start('scene-10'));move(bed.icon,{left:14,top:105,width:190,height:210},start('scene-10'));move(bed.label,{left:17,fontSize:30},start('scene-10'));move(bed.field,{left:15,top:350,width:192,height:100,fontSize:22},start('scene-10'));move(bed.method,{left:15,top:465,width:192,height:85,fontSize:18},start('scene-10'));
const selfTag=box('self-tag',760,480,248,370,'#8ce4ff');txt(selfTag,'self',24,35,48,'mono');txt(selfTag,'=',89,115,52,'mono');txt(selfTag,'desk',24,220,48,'mono');show(selfTag,cue('scene-10','self ở đây'));hide(selfTag,start('scene-11'));
const operation=txt(desk.root,'self.on = True',30,665,46,'mono');concealed(operation);reveal(operation,cue('scene-10','Thuộc tính on'));
const commit=cue('scene-10','chuyển thành đúng');wire('method-writes-field','M595 1070 V1250 l-13 -18 m13 18 l13 -18',cue('scene-10','Thuộc tính on'),start('scene-11'));token('True',430,1160,350,1330,commit-.7,.7);value(desk.val,'True',commit);tl.fromTo(desk.root.querySelector('.beam'),{opacity:0},{opacity:1,duration:.25,immediateRender:false},commit);tl.fromTo(desk.root.querySelector('.bulb'),{fill:'#e5e5e5'},{fill:'#feee91',duration:.25,immediateRender:false},commit);samples.push({job:'state commit desk only',start:commit-.05,end:commit+.35});
// 11: inspect the other receiver at readable scale, keep changed desk as witness.
heading('scene-11','Còn chiếc đèn ngủ?');hide(operation,start('scene-11'));move(desk.root,{left:64,top:995,width:300,height:580},start('scene-11'));move(desk.icon,{left:30,top:105,width:235,height:210},start('scene-11'));move(desk.field,{left:18,top:335,width:255,height:110,fontSize:28},start('scene-11'));move(desk.method,{left:18,top:465,width:255,height:86,fontSize:20},start('scene-11'));move(bed.root,{left:430,top:450,width:578,height:1125},start('scene-11'));move(bed.icon,{left:135,top:125,width:300,height:290},start('scene-11'));move(bed.label,{left:30,fontSize:42},start('scene-11'));move(bed.field,{left:28,right:'auto',top:510,bottom:'auto',width:514,height:190,fontSize:50},start('scene-11'));move(bed.method,{left:28,right:'auto',top:780,bottom:'auto',width:514,height:150,fontSize:37},start('scene-11'));
const noCall=box('no-call',460,1440,514,100,'#fff');txt(noCall,'Không nhận lời gọi',20,24,31);show(noCall,cue('scene-11','không nhận lời gọi'));hide(noCall,start('scene-12'));
// 12: restore equal scale so comparison is about state, not panel size.
heading('scene-12','Cùng cách bật.\nTrạng thái riêng.');
for(const[o,x]of[[desk,64],[bed,560]]){move(o.root,{left:x,top:755,width:440,height:825},start('scene-12'));move(o.label,{left:30,fontSize:38},start('scene-12'));move(o.icon,{left:75,top:115,width:280,height:260},start('scene-12'));move(o.field,{left:28,top:475,width:376,height:145,fontSize:39},start('scene-12'));move(o.method,{left:28,top:665,width:376,height:115,fontSize:29},start('scene-12'));}
const shared=box('shared-method',64,400,948,235,'#8ce4ff');txt(shared,'LỚP Lamp · DÙNG CHUNG',28,22,25,'eyebrow');txt(shared,'turn_on(self)',28,87,55,'mono');show(shared,cue('scene-12','dùng chung cách bật'));wire('shared-left','M535 650 V695 H284 V740 l-12 -16 m12 16 l12 -16',cue('scene-12','định nghĩa trong lớp'),start('scene-13'));wire('shared-right','M535 650 V695 H780 V740 l-12 -16 m12 16 l12 -16',cue('scene-12','định nghĩa trong lớp'),start('scene-13'));hide(shared,start('scene-13'));
// 13: state + method become a single large object view, not disconnected fact cards.
heading('scene-13','Đối tượng tổ chức\ndữ liệu và hành vi');hide(bed.root,start('scene-13'));move(desk.root,{left:64,top:440,width:948,height:1140},start('scene-13'));move(desk.icon,{left:325,top:100,width:280,height:250},start('scene-13'));move(desk.field,{left:30,top:500,width:418,height:215,fontSize:42},cue('scene-13','chứa dữ liệu'));move(desk.method,{left:490,top:500,width:418,height:215,fontSize:33},cue('scene-13','gọi hành vi'));wire('behavior-affects-owned-state','M780 1195 V1400 H280 V1195 l-12 16 m12 -16 l12 16',cue('scene-13','thay đổi dữ liệu'),start('outro'));hide(desk.root,start('outro'));
// 14: rule poster with the exact demonstrated relationship, no new concept.
const final=box('rule-poster',64,190,948,990,'#2d3436');txt(final,'OOP',40,30,34,'eyebrow').style.color='#feee91';const rTitle=txt(final,'Dữ liệu\n+ hành vi',40,135,98,'title',850);Object.assign(rTitle.style,{visibility:'visible',color:'#feee91',whiteSpace:'pre-line',left:'40px',top:'135px',width:'850px',fontSize:'98px'});const enclosed=box('rule-enclosure',38,535,864,300,'#fff',final);txt(enclosed,'MỘT ĐỐI TƯỢNG',30,30,32,'eyebrow');txt(enclosed,'desk.on  →  True',30,120,44,'mono');show(final,start('outro')+.05);show(enclosed,cue('outro','dữ liệu cùng hành vi'));
const ruleRel=box('rule-relation',64,1220,948,365,'#8ce4ff');txt(ruleRel,'class  →  object',35,35,57,'mono');const relationNote=concealed(txt(ruleRel,'Mô tả chung     Đối tượng cụ thể',35,145,30));const boundary=concealed(txt(ruleRel,'Ví dụ dùng lớp · chưa đi vào kế thừa',35,255,25));show(ruleRel,cue('outro','Lớp mô tả'));reveal(relationNote,cue('outro','đối tượng cụ thể'));reveal(boundary,cue('outro','ví dụ dùng lớp'));
// Captions stay on a stable surface; words do not count toward model motion.
const band=document.getElementById('captions');sections.forEach(s=>{const chunks=[];let line=[];for(const w of s.words){if(line.length&&line.map(x=>x.w).join(' ').length+w.w.length+1>38){chunks.push(line);line=[];}line.push(w);}if(line.length)chunks.push(line);chunks.forEach((words,i)=>{const e=el('div','caption-line',band);const st=Math.max(s.start,words[0].t0-.06),en=Math.min(s.start+s.dur,i+1<chunks.length?chunks[i+1][0].t0-.06:words.at(-1).t1+.25);tl.set(e,{opacity:1},st);tl.set(e,{opacity:0},en);words.forEach((w,j)=>{if(j)e.appendChild(document.createTextNode(' '));const sp=el('span','caption-word',e,w.w);tl.set(sp,{backgroundColor:'#feee91'},w.t0);});});});
tl.to(document.getElementById('progress'),{width:1040,duration:P.total,ease:'none'},0);window.StoryTimeline=tl;window.COMMIT_TIME=commit;
})();
