const puppeteer=require('puppeteer-core'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const dir=path.resolve(__dirname,'..'),browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--allow-file-access-from-files']}),page=await browser.newPage(),errors=[];await page.setViewport({width:1080,height:1920});page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',r=>r.url().includes('gsap.min.js')?r.respond({status:200,contentType:'application/javascript',body:fs.readFileSync(path.join(dir,'assets/js/gsap.min.js'))}):r.continue());await page.goto('file://'+dir+'/index.html');await page.evaluate(()=>document.fonts.ready);if(errors.length)throw Error(errors.join('\n'));await page.waitForFunction(()=>!!window.StoryTimeline);fs.mkdirSync(dir+'/snapshots',{recursive:true});const {plan,ops,reveals,emphasis}=await page.evaluate(()=>({plan:PLAN,ops:OPERATION_SAMPLES,reveals:REVEAL_SAMPLES,emphasis:EMPHASIS_SAMPLES}));const seek=async t=>page.evaluate(t=>{window.StoryTimeline.seek(t,false);},t);
const inspect=()=>page.evaluate(()=>{
const visible=e=>{for(let p=e;p;p=p.parentElement){let s=getComputedStyle(p);if(s.visibility==='hidden'||s.display==='none'||+s.opacity<.98)return false;}return true;};
const rgb=s=>{const a=s.match(/[\d.]+/g)?.map(Number);return a?.length>=3?a:null;};const lum=a=>a.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((t,v,i)=>t+v*[.2126,.7152,.0722][i],0);
const pairs=[],overflow=[];for(const e of document.querySelectorAll('.copy,.chip,.rail-item,.bento-accent,.memory-cell,.brand,.edition,#footer,.caption-word')){if(!visible(e))continue;const r=e.getBoundingClientRect();if(!r.width||!r.height)continue;if(e.scrollWidth>e.clientWidth+3||r.right>1025||r.bottom>1900)overflow.push({id:e.id,text:e.textContent,width:r.width,scroll:e.scrollWidth,right:r.right,bottom:r.bottom});let bg=null;for(let p=e;p&&!bg;p=p.parentElement){const a=rgb(getComputedStyle(p).backgroundColor);if(a&&(a.length<4||a[3]===1))bg=a;}bg??=[229,229,229];const fg=rgb(getComputedStyle(e).color);if(fg){const x=lum(fg),y=lum(bg),ratio=(Math.max(x,y)+.05)/(Math.min(x,y)+.05);pairs.push({id:e.id,text:e.textContent.slice(0,60),fg,bg,ratio});}}
return {captionCount:[...document.querySelectorAll('.caption-line')].filter(e=>+getComputedStyle(e).opacity>.01).length,overflow,contrast:pairs.filter(x=>x.ratio<4.49),minContrast:Math.min(...pairs.map(x=>x.ratio))};});
const geometry=()=>page.evaluate(()=>[...document.querySelectorAll('.shot')].filter(e=>getComputedStyle(e).visibility==='visible').map(e=>[e.id,...[...e.querySelectorAll('.panel,.copy,.chip,.memory-cell')].map(n=>{const r=n.getBoundingClientRect();return [n.id,n.textContent,getComputedStyle(n).visibility,...[r.x,r.y,r.width,r.height].map(x=>Math.round(x*10)/10)];})]));
const reports=[],baselines=[];
for(let i=0;i<plan.sections.length;i++){const s=plan.sections[i],t=s.start+s.dur-.6;await seek(t);await page.screenshot({path:dir+`/snapshots/scene-${String(i).padStart(2,'0')}.png`});reports.push({i,t,...await inspect()});baselines.push({t,g:await geometry()});}
for(const i of [22,3,10,2,14,5,0,21,17,4,23,13,7]){await seek(baselines[i].t);assert.deepEqual(await geometry(),baselines[i].g,'Reverse seek scene '+i);}
const samples=ops.filter(o=>/transfer|commit|enclose|overlap|call native|append|kernel|reject/.test(o.job));for(let i=0;i<samples.length;i++){const o=samples[i];for(const [suffix,t]of[['before',Math.max(0,o.start-.04)],['mid',(o.start+o.end)/2],['after',o.end+.04]]){await seek(t);await page.screenshot({path:dir+`/snapshots/op-${String(i).padStart(2,'0')}-${suffix}.png`});}}
// Verify delayed native reveal remains hidden before its cue, even after a late seek.
const revealFailures=[];for(const r of reveals){if(r.t<.1)continue;await seek(r.t-.04);const v=await page.$eval('#'+r.id,e=>getComputedStyle(e).visibility==='visible'&&+getComputedStyle(e).opacity>.01);if(v)revealFailures.push(r);}
for(const o of ops.filter(o=>o.job.startsWith('commit '))){await seek(o.start+.02);assert.equal(await page.$eval('#'+o.id,e=>e.textContent),o.job.slice(7),'Committed state '+o.job);}assert.deepEqual(reports.flatMap(r=>r.overflow),[]);assert.deepEqual(reports.flatMap(r=>r.contrast),[]);assert.deepEqual(revealFailures,[]);assert.ok(reports.every(r=>r.captionCount===1),'One caption line at sampled readable times');assert.deepEqual(errors,[]);fs.writeFileSync(dir+'/snapshots/qa.json',JSON.stringify({reports,ops,reveals,emphasis,reverseSeek:'pass',committedStates:'pass',revealFailures,errors},null,2));await browser.close();console.log(JSON.stringify({issues:reports.filter(x=>x.overflow.length||x.contrast.length),revealFailures,operations:ops.length,emphasis:emphasis.length},null,2));})().catch(e=>{console.error(e);process.exit(1)});
