const StudyTimeline=gsap.timeline({paused:true}),STUDY_OPS=[];window.StudyTimeline=StudyTimeline;window.STUDY_OPS=STUDY_OPS;
const n=Object.fromEntries([...document.querySelectorAll('[data-native-node]')].map(e=>[e.dataset.nativeNode,e]));
const record=(node,t,d,kind,job)=>STUDY_OPS.push({id:node.id,start:t,end:t+d,kind,job});
const native=ArchitectNative.create(StudyTimeline,record),editorial=ArchitectEditorial.create(StudyTimeline,record);
gsap.set(['source','destination','assignment','update','bridge','copy-note','result','evidence'].map(id=>n[id]),{autoAlpha:0,y:16});
const show=(id,at)=>StudyTimeline.fromTo(n[id],{autoAlpha:0,y:16},{autoAlpha:1,y:0,duration:.45,immediateRender:false},at);
const text=(id,before,after,at)=>StudyTimeline.fromTo(n[id],{textContent:before},{textContent:after,duration:0,immediateRender:false},at);
show('source',.8);show('destination',1.5);
StudyTimeline.set(n.initial,{visibility:'hidden'},3);show('assignment',3);show('bridge',4);
text('caption','Nếu đổi x sau phép gán, y có đổi theo không?','Đọc 10 từ x, rồi sao chép giá trị ấy vào y.',3);
native.copyValue({source:n['source-value'],destination:n['destination-value'],token:n.token,value:'10',before:'?',at:4.5,duration:1.2,from:{left:236,top:840},to:{left:704,top:840}});
show('copy-note',5.9);record(n['copy-note'],5.9,.45,'disclosure','explain preserved source');
StudyTimeline.set([n.assignment,n.bridge],{visibility:'hidden'},8);show('update',8);
text('caption','Đọc 10 từ x, rồi sao chép giá trị ấy vào y.','Bây giờ ghi 20 vào x. Chỉ x thay đổi.',8);
native.writeValue({destination:n['source-value'],before:'10',value:'20',at:9,duration:.5});
text('copy-note','Nguồn vẫn giữ 10. Đích nhận một bản sao.','x đã đổi. y vẫn giữ giá trị được sao chép trước đó.',9.6);
show('result',10.4);record(n.result,10.4,.45,'disclosure','compare actual final values');
StudyTimeline.to(n['copy-note'],{autoAlpha:0,duration:.2},11.8);
editorial.resultToEvidence({at:12,duration:.8,tracks:[{node:n.result,from:{top:1260,fontSize:112},to:{top:1190,fontSize:92}},{node:n.evidence,from:{top:1400},to:{top:1350}}]});show('evidence',12.8);
text('caption','Bây giờ ghi 20 vào x. Chỉ x thay đổi.','Phép gán đã thực hiện xong; nó không tự chạy lại.',12.8);
// Hold for reading the two final values and the bounded rule, not decorative drift.
StudyTimeline.to(n.foot,{opacity:1,duration:4},14);
StudyTimeline.seek(0,false);
const play=document.getElementById('play'),seek=document.getElementById('seek'),backgroundToggle=document.getElementById('background-toggle');
if(play)play.onclick=()=>StudyTimeline.paused(!StudyTimeline.paused());
if(seek)seek.oninput=e=>StudyTimeline.pause().seek(+e.target.value,false);
if(backgroundToggle)backgroundToggle.onchange=e=>n.backdrop.style.display=e.target.checked?'block':'none';
if(seek)StudyTimeline.eventCallback('onUpdate',()=>seek.value=StudyTimeline.time());
