function initSrpStory(){'use strict';
const P=window.PLAN,S=window.SCORE,tl=gsap.timeline({paused:true}),D=document.getElementById('srp-diagram'),O=document.getElementById('srp-foreground'),OPS=[],REV=[],CHECKS=[];let serial=0;
const C={orange:'#D97757',purple:'#C4B5FD',blue:'#93C5FD',ink:'#E2E8F0',muted:'#94A3B8',green:'#86EFAC'};
const E=(tag,cls,parent,text)=>{if(!parent)throw Error('Missing parent for '+cls);const n=document.createElement(tag);n.className=cls;n.id='n'+(++serial);if(text!=null)n.textContent=text;parent.appendChild(n);return n;};
const rect=(n,x,y,w,h)=>{Object.assign(n.style,{left:x+'px',top:y+'px',width:w+'px',...(h?{height:h+'px'}:{})});return n;};
const text=(parent,str,x,y,w,size=38,cls='')=>{const n=rect(E('div','copy '+cls,parent,str),x,y,w);n.style.fontSize=size+'px';return n;};
function norm(s){return String(s).toLowerCase().normalize('NFC').match(/[\p{L}\p{N}]+/gu)||[];}
function at(i,k){const needle=norm(typeof k==='number'?S[i].cues[k]:k),words=P.sections[i].words.flatMap(w=>norm(w.w).map(s=>({s,t:w.t0})));let j=words.findIndex((_,j)=>needle.every((s,z)=>words[j+z]?.s===s));if(j<0)throw Error('Missing cue '+i+' / '+k);return words[j].t;}
function show(n,t,d=.35,why='reveal'){gsap.set(n,{autoAlpha:0,display:'none'});tl.set(n,{display:'block',visibility:'visible'},t);tl.to(n,{opacity:1,duration:d},t);REV.push({id:n.id,t,why});}
function appear(n,t,d=.3){tl.set(n,{display:'block',visibility:'visible'},t);tl.to(n,{opacity:1,duration:d},t);}
function hide(n,t,d=.25){tl.to(n,{opacity:0,duration:d},t);tl.set(n,{display:'none',visibility:'hidden'},t+d);}
function move(n,vars,t,d=.65,job='reframe'){tl.to(n,{...vars,duration:d,ease:'power2.inOut'},t);OPS.push({id:n.id,start:t,end:t+d,job});}
const oldFields=new Map();function write(n,value,t,job='state commit'){const prev=oldFields.has(n)?oldFields.get(n):n.textContent;tl.fromTo(n,{textContent:prev},{textContent:value,duration:0,immediateRender:false},t);oldFields.set(n,value);OPS.push({id:n.id,start:t,end:t+.02,job});}
function focus(n,t,col=C.orange){tl.to(n,{borderColor:col,boxShadow:'0 0 35px '+col+'22',duration:.25},t);}
function clearFocus(n,t){tl.to(n,{borderColor:'#ffffff38',boxShadow:'0 24px 70px #0005',duration:.25},t);}
function route(g,points,t,col=C.orange,d=.6){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('route-svg');svg.setAttribute('viewBox','0 0 1080 1920');g.appendChild(svg);const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',points);path.style.stroke=col;svg.appendChild(path);let len=path.getTotalLength();gsap.set(path,{strokeDasharray:len,strokeDashoffset:len});tl.to(path,{strokeDashoffset:0,duration:d,ease:'none'},t);OPS.push({id:g.id,start:t,end:t+d,job:'route'});return svg;}
function token(g,label,x,y,tx,ty,t,d=.65,col=C.orange){const n=rect(E('div','token',g,label),x,y,0);n.style.width='auto';n.style.borderColor=col;show(n,t,.05,'travelling data/request');move(n,{left:tx,top:ty},t,d,'transfer '+label);hide(n,t+d,.12);return n;}
const scenes=P.sections.map((s,i)=>{const n=E('div','shot',document.getElementById('srp-stage'));n.id='shot-'+i;tl.set(n,{display:'block',visibility:'visible'},s.start);tl.set(n,{display:'none',visibility:'hidden'},s.start+s.dur);tl.set(document.getElementById('phase'),{textContent:['QUESTION','SETUP','DECODE','EXECUTE','VERIFY','RULE'][['question','setup','decode','execute','verify','outro'].indexOf(S[i].phase)]+' /// SOLID / S'},s.start);tl.set(document.getElementById('counter'),{textContent:String(i+1).padStart(2,'0')+' / '+P.sections.length},s.start);return n;});
const fronts=P.sections.map((s,i)=>{const n=E('div','shot',O);n.id='front-'+i;tl.set(n,{display:'block',visibility:'visible'},s.start);tl.set(n,{display:'none',visibility:'hidden'},s.start+s.dur);return n;});
function title(i,str,x=72,y=220,w=936,size=78,t){const n=text(scenes[i],str,x,y,w,size,'display');show(n,t??P.sections[i].start+.12);return n;}
function badge(g,str,x,y,t,col){if(g.id.startsWith('shot-'))g=fronts[Number(g.id.slice(5))];const n=rect(E('div','badge',g,str),x,y,0);n.style.width='auto';if(col)n.style.color=col;show(n,t);return n;}
function evidence(i,str,x,y,w,t){const n=rect(E('div','evidence',scenes[i],str),x,y,w);show(n,t);return n;}
const owner=rect(E('div','owned owner',D),170,660,840,700);owner.id='invoice-owner';E('div','owner-title',owner,'class Invoice');E('div','owner-rule',owner);
function method(id,label,name,x,y,w,h,role,surface){const root=rect(E('div','owned method',D),x,y,w,h);root.id=id;root.style.setProperty('--role',role);root.style.setProperty('--surface',surface);const identity=E('div','identity',root,label),heading=E('div','name',root,name),body=E('div','body',root),footer=E('div','footer',root);return {root,identity,heading,body,footer};}
const calc=method('calc','HÀM / total()','Tính tiền',215,815,750,205,C.orange,'#241813');
const c1=E('div','',calc.body,'subtotal = 100_000'),c2=E('div','active-code',calc.body,'discount = 0%'),c3=E('div','',calc.body,'total = 100_000');
const view=method('presenter','HÀM / render()','Trình bày bản in',215,1070,750,205,C.purple,'#1C162B');
const v1=E('div','active-code',view.body,'title = "HÓA ĐƠN"'),v2=E('div','',view.body,'amount = total');
const data=rect(E('div','data',D,'DỮ LIỆU · 100.000 đồng'),112,555,856,85);data.id='invoice-data';
show(owner,at(0,1));show(calc.root,at(0,1)+.1);show(view.root,at(0,1)+.22);gsap.set([calc.body,view.body],{autoAlpha:0});
function pose(m,x,y,w,h,t,body=false,d=.65){move(m.root,{left:x,top:y,width:w,height:h},t,d,'inspect/reframe '+m.root.id);tl.to(m.body,{autoAlpha:body?1:0,duration:.25},t+.2);tl.to(m.heading,{fontSize:w<480?32:43,duration:d},t);tl.to(m.identity,{fontSize:w<480?19:23,duration:d},t);}
// 0: an incident is primary, not a decorative title page.
{const i=0,g=scenes[i];title(i,'Đổi mẫu in.\nMở cả lớp tính tiền?',72,265,910,86,at(i,0));const req=rect(E('div','request purple',g),72,500,540,125);E('div','who',req,'YÊU CẦU');E('div','',req,'Đổi tiêu đề hóa đơn');show(req,at(i,0));route(g,'M580 625 V720 H750',at(i,1),C.purple);badge(g,'2 lý do thay đổi?',72,1450,at(i,2));}
// 1–2: the owner opens; actual operations take the available area.
{let i=1;title(i,'Một lớp chứa gì?',72,235,930,70);move(owner,{left:72,top:445,width:936,height:1130},P.sections[i].start);pose(calc,116,680,848,355,at(i,1),true);pose(view,116,1130,848,335,at(i,2),true);show(data,at(i,1));move(data,{left:112,top:555,width:856,height:85},at(i,1));}
{const i=2,g=scenes[i];title(i,'Cùng một lớp.\nAi yêu cầu thay đổi?',72,230,936,72);focus(calc.root,at(i,0));clearFocus(calc.root,at(i,1));focus(view.root,at(i,1),C.purple);badge(g,'TÍNH TIỀN',600,1047,at(i,0),C.orange);badge(g,'MẪU BẢN IN',580,1490,at(i,1),C.purple);}
// 3–4: different request origins converge on the same class boundary.
function request(i,who,msg,x,y,w,t,col){const r=rect(E('div','request '+col,scenes[i]),x,y,w,150);E('div','who',r,who);E('div','',r,msg);show(r,t);return r;}
{const i=3,g=scenes[i];request(i,'KINH DOANH','Đổi mức giảm giá',72,225,620,at(i,0),'orange');route(g,'M694 302 H1015 V860 H965',at(i,1),C.orange);focus(calc.root,at(i,1));clearFocus(view.root,at(i,0));token(g,'Yêu cầu',845,330,830,775,at(i,1),.65);badge(g,'Mẫu in giữ nguyên',550,1490,at(i,2),C.purple);}
{const i=4,g=scenes[i];request(i,'VẬN HÀNH','Đổi tiêu đề bản in',72,225,620,at(i,0),'purple');route(g,'M694 302 H1015 V1290 H966',at(i,1),C.purple);focus(view.root,at(i,1),C.purple);clearFocus(calc.root,at(i,0));token(g,'Yêu cầu',845,330,830,1220,at(i,1),.8,C.purple);badge(g,'Kinh doanh → tính tiền',90,365,at(i,2),C.orange);badge(g,'Vận hành → mẫu in',550,365,at(i,2),C.purple);}
// 5: density release only after showing both causes. Definition is now earned.
{const i=5,g=scenes[i];title(i,'S',72,245,270,220,at(i,0));const full=text(g,'SINGLE RESPONSIBILITY\nPRINCIPLE',345,335,670,36,'mono');show(full,at(i,0));title(i,'Một lý do\nđể thay đổi.',72,610,936,104,at(i,1));const sub=text(g,'Một nhóm nhu cầu gắn kết',78,895,930,38,'muted');show(sub,at(i,1)+.4);move(owner,{left:72,top:1090,width:936,height:480},P.sections[i].start,.6);pose(calc,112,1220,410,260,P.sections[i].start,false);pose(view,558,1220,410,260,P.sections[i].start,false);hide(data,P.sections[i].start);clearFocus(view.root,P.sections[i].start);badge(g,'2 lý do đang chung một nơi',170,1590,at(i,2));}
// 6–7: SAME method nodes leave their common owner. Shared data stays outside.
{const i=6,g=scenes[i];title(i,'Tách theo lý do.',72,240,936,82,at(i,0));appear(data,at(i,1));move(data,{left:72,top:415,width:936,height:85},at(i,1));move(owner,{left:520,top:960,width:488,height:610},P.sections[i].start,.55);pose(view,558,1100,410,330,P.sections[i].start,false);pose(calc,72,590,936,350,at(i,2),true);write(calc.identity,'LỚP / InvoiceCalculator',at(i,2)+.45);write(calc.footer,'Lý do đổi: chính sách tính tiền',at(i,2)+.5);CHECKS.push({t:at(i,2)+.8,check:'calc extracted'});}
{const i=7,g=scenes[i];title(i,'Mỗi phần một chủ.',72,240,936,82);pose(view,72,1090,936,470,at(i,0),true);write(view.identity,'LỚP / InvoicePresenter',at(i,0)+.45);write(view.footer,'Lý do đổi: yêu cầu bản in',at(i,0)+.5);hide(owner,at(i,0)+.4);evidence(i,'Hai phần việc cũ → hai ranh giới',72,974,936,at(i,1));CHECKS.push({t:at(i,0)+.9,check:'both extracted'});}
// 8: reflow peers into a collaboration path. The arrows now mean DATA, explicitly labeled.
const paper=rect(E('div','paper',D),520,1310,488,295);paper.id='paper';const paperTitle=E('div','paper-title',paper,'HÓA ĐƠN');E('div','paper-line',paper);const paperNote=E('div','paper-note',paper,'TỔNG PHẢI TRẢ');const amount=E('div','paper-amount',paper,'100.000 đ');
{const i=8,g=scenes[i];title(i,'Phối hợp bằng dữ liệu',72,220,936,68);appear(data,P.sections[i].start);move(data,{left:72,top:375,width:760,height:85},P.sections[i].start);pose(calc,72,570,620,290,P.sections[i].start,false);pose(view,388,965,620,290,P.sections[i].start,false);write(calc.footer,'Nhận dữ liệu → trả số tiền',P.sections[i].start);write(view.footer,'Nhận số tiền → tạo bản in',P.sections[i].start);route(g,'M380 465 V555 l-12 -18 m12 18 l12 -18',at(i,0),C.blue);token(g,'100.000',380,455,300,690,at(i,0),.55,C.blue);route(g,'M698 720 H880 V950 l-12 -18 m12 18 l12 -18',at(i,1));token(g,'100.000',635,780,755,1080,at(i,1),.6);route(g,'M730 1257 V1297 l-12 -18 m12 18 l12 -18',at(i,2),C.purple,.3);show(paper,at(i,2)+.25);badge(g,'LUỒNG DỮ LIỆU',72,950,at(i,1),C.blue);const n=text(g,'Tách trách nhiệm\nvẫn phối hợp.',72,1360,410,39,'display');show(n,at(i,3));}
// 9–10: editing and running are separate actions; unchanged code can render a new total.
{const i=9,g=scenes[i];title(i,'01 / Đổi chính sách',72,235,936,74);hide(paper,P.sections[i].start);hide(data,P.sections[i].start);pose(calc,72,465,936,620,P.sections[i].start,true);pose(view,590,1240,418,295,P.sections[i].start,false);write(calc.footer,'KINH DOANH · quy tắc giảm giá',P.sections[i].start);write(view.footer,'Mã trình bày giữ nguyên',P.sections[i].start);const old=text(g,'0%',112,1160,380,116,'display accent');show(old,at(i,0));write(c2,'discount = 10%',at(i,1));write(old,'10%',at(i,1));focus(calc.root,at(i,2));badge(g,'Không sửa ở đây',588,1560,at(i,3),C.purple);}
{const i=10,g=scenes[i];title(i,'Chạy lại cùng dữ liệu',72,235,936,72);const eq=text(g,'100.000 × (1 − 10%)',95,360,910,40,'mono');show(eq,at(i,0));write(c3,'total = 90_000',at(i,1));const res=text(g,'90.000 đ',90,1100,460,92,'display accent');show(res,at(i,1));token(g,'90.000',370,980,750,1410,at(i,2)-.45,.5);badge(g,'Dữ liệu mới / mã cũ',540,1560,at(i,3),C.purple);move(paper,{left:72,top:1250,width:450,height:350},P.sections[i].start);tl.set(amount,{fontSize:44},P.sections[i].start);appear(paper,at(i,2)+.15);write(amount,'90.000 đ',at(i,2)+.1);CHECKS.push({t:at(i,3)+.3,check:'discount total'});}
// 11: same verification grammar, opposite active owner. Invariant is pricing, edit is formatting.
{const i=11,g=scenes[i];title(i,'02 / Đổi mẫu bản in',72,235,936,74);hide(paper,P.sections[i].start);pose(view,72,465,936,620,P.sections[i].start,true);pose(calc,72,1230,440,320,P.sections[i].start,false);clearFocus(calc.root,P.sections[i].start);write(calc.footer,'Giảm giá: 10% · không đổi',P.sections[i].start);write(view.footer,'VẬN HÀNH · tiêu đề bản in',P.sections[i].start);write(v1,'title = "PHIẾU THANH TOÁN"',at(i,1));focus(view.root,at(i,2),C.purple);const keep=text(g,'10%',620,1210,380,124,'display accent');show(keep,at(i,3));badge(g,'Giữ chính sách tính tiền',535,1430,at(i,3),C.orange);}
// 12: actual output is now dominant; code collapses to context.
{const i=12,g=scenes[i];title(i,'Đổi tiêu đề.\nGiữ đúng số tiền.',72,225,936,80);pose(view,72,485,936,160,P.sections[i].start,false);tl.to(view.heading,{fontSize:34},P.sections[i].start);tl.to(view.footer,{autoAlpha:0,duration:.2},P.sections[i].start);pose(calc,72,1380,440,245,P.sections[i].start,false);tl.to(calc.footer,{fontSize:20},P.sections[i].start);move(paper,{left:220,top:770,width:720,height:515},P.sections[i].start);appear(paper,at(i,0));write(paperTitle,'PHIẾU\nTHANH TOÁN',at(i,1));tl.to(amount,{fontSize:76,duration:.4},at(i,2));badge(g,'✓ Tiền vẫn 90.000',520,1390,at(i,2),C.green);badge(g,'2 nơi sửa riêng',520,1500,at(i,3));CHECKS.push({t:at(i,3)+.25,check:'format isolation'});}
// 13: several cohesive operations inside one responsibility boundary.
{const i=13,g=scenes[i];hide(paper,P.sections[i].start);hide(view.root,P.sections[i].start);title(i,'Một trách nhiệm\ncó thể có nhiều hàm.',72,235,936,81,at(i,0));pose(calc,72,565,936,1020,P.sections[i].start,false);write(calc.footer,'Cùng phục vụ quy tắc tính tiền',at(i,3));tl.to(calc.footer,{fontSize:29,duration:.3},at(i,3));const defs=[['subtotal()','Cộng tiền hàng',1],['reduction()','Tính phần giảm giá',2],['total()','Tính số phải trả',3]];defs.forEach(([name,desc,k],j)=>{const box=rect(E('div','request orange',fronts[i]),112,795+j*210,852,155);E('div','who',box,name);E('div','',box,desc);show(box,at(i,k));move(box,{left:132,width:812},at(i,k),.5,'group operation inside one responsibility');});}
// 14: known request sources route to known owners. Fewer words, same evidence.
{const i=14,g=scenes[i];title(i,'Ai cần đổi?\nĐổi vì điều gì?',72,250,936,98,at(i,0));pose(calc,562,845,446,260,P.sections[i].start,false);appear(view.root,P.sections[i].start+.7);pose(view,562,1220,446,260,P.sections[i].start,false);tl.to(view.footer,{autoAlpha:1,duration:.2},P.sections[i].start);write(calc.footer,'Quy tắc tính tiền',P.sections[i].start);write(view.footer,'Yêu cầu trình bày',P.sections[i].start);request(i,'KINH DOANH','Chính sách giá',72,860,390,at(i,1),'orange');request(i,'VẬN HÀNH','Mẫu bản in',72,1235,390,at(i,2),'purple');route(g,'M467 950 H547 l-16 -12 m16 12 l-16 12',at(i,1),C.orange);route(g,'M467 1325 H547 l-16 -12 m16 12 l-16 12',at(i,2),C.purple);evidence(i,'Gom cùng lý do.\nTách lý do độc lập.',72,570,936,at(i,1));badge(g,'S / SINGLE RESPONSIBILITY',220,1550,at(i,3));}
// Karaoke: source wording retained, a single phrase band, no meaningless motion.
P.sections.forEach(sec=>{const chunks=[];let line=[];for(const w of sec.words){if(line.length&&line.map(x=>x.w).join(' ').length+w.w.length+1>45){chunks.push(line);line=[];}line.push(w);}if(line.length)chunks.push(line);if(chunks.length>1&&chunks.at(-1).length<=2)chunks[chunks.length-2].push(...chunks.pop());chunks.forEach((words,i)=>{const n=E('div','caption-line',document.getElementById('captions'));let a=Math.max(sec.start,words[0].t0-.03),b=i+1<chunks.length?chunks[i+1][0].t0-.03:sec.start+sec.dur-.05;tl.set(n,{opacity:1},a);tl.set(n,{opacity:0},b);words.forEach((w,j)=>{if(j)n.appendChild(document.createTextNode(' '));const sp=E('span','caption-word',n,w.w);tl.set(sp,{color:'#F8FAFC',backgroundColor:'#482C22'},w.t0);});});});
tl.to(document.getElementById('progress'),{width:780,duration:P.total,ease:'none'},0);
window.StoryTimeline=tl;window.OPERATION_SAMPLES=OPS;window.REVEAL_SAMPLES=REV;window.STATE_CHECKS=CHECKS;
window.__timelines={'noir-story':tl};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initSrpStory,{once:true});else initSrpStory();
