const path=require('path'),fs=require('fs'),assert=require('assert'),pp=require('puppeteer-core');
(async()=>{const dir=path.resolve(process.argv[2]),browser=await pp.launch({executablePath:process.argv[3]||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--allow-file-access-from-files']});try{const page=await browser.newPage();await page.setViewport({width:1080,height:1920});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+dir+'/index.html');await page.evaluate(()=>document.fonts.ready);assert.deepEqual(errors,[]);assert(await page.evaluate(()=>!!window.__timelines?.['mint-bento-programming']));
 const commits=await page.evaluate(()=>MINT_COMMITS),sections=await page.evaluate(()=>PLAN.sections);fs.mkdirSync(dir+'/qa',{recursive:true});
 const state=async t=>{await page.evaluate(t=>{__timelines['mint-bento-programming'].seek(t,false)},t);return page.evaluate(()=>{const vis=e=>{for(let n=e;n instanceof Element;n=n.parentElement){const s=getComputedStyle(n);if(s.display==='none'||s.visibility==='hidden'||+s.opacity===0)return false;}return true;};const p=[...document.querySelectorAll('.page')].find(vis);return {page:p.dataset.section,items:[...p.querySelectorAll('[data-item]')].filter(vis).map(e=>e.textContent),counts:[...p.querySelectorAll('[data-count]')].filter(vis).map(e=>+e.textContent),proxy:[...p.querySelectorAll('[data-proxy]')].filter(vis).map(e=>{const r=e.getBoundingClientRect();return [e.textContent,+r.x.toFixed(2),+r.y.toFixed(2)]})};});};
 const expected={},times=[.1,...sections.map(p=>p.start+p.dur-.4)];for(const c of commits)times.push(c.start-.05,c.start+.3,c.commit+.01);
 for(const t of times){expected[t]=await state(t);await page.screenshot({path:dir+'/qa/t-'+t.toFixed(3)+'.png'});}
 for(const c of commits){const before=expected[c.start-.05],mid=expected[c.start+.3],after=expected[c.commit+.01];assert.equal(before.items.length,c.before);assert.deepEqual(before.counts,[c.before]);assert.equal(mid.items.length,c.before);assert.deepEqual(mid.counts,[c.before]);assert.equal(mid.proxy.length,1);assert.equal(after.items.length,c.after);assert.deepEqual(after.counts,[c.after]);assert.equal(after.items.at(-1),c.item);assert.deepEqual(after.proxy,[]);assert.deepEqual(after.items.slice(0,-1),before.items);}
 const inspect=expected[sections[2].start+sections[2].dur-.4];assert.deepEqual(inspect.items,['A','B','C']);assert.deepEqual(inspect.counts,[3]);
 for(const t of [...times].reverse())assert.deepEqual(await state(t),expected[t],'reverse seek '+t);
 for(const p of sections){await state(p.start+p.dur-.4);assert.deepEqual(await page.evaluate(()=>[...document.querySelectorAll('.page')].filter(p=>getComputedStyle(p).display!=='none').flatMap(p=>[...p.querySelectorAll('.placed')].filter(e=>e.scrollWidth>e.clientWidth+3).map(e=>e.textContent))),[]);}
 // Synthetic timestamps exercise captions, not voice quality.
 await page.evaluate(()=>{__timelines['mint-bento-programming'].kill();document.getElementById('pages').replaceChildren();document.getElementById('captions').replaceChildren();[SCRIPT.intro,...SCRIPT.scenes,SCRIPT.outro].forEach((c,i)=>{const p=PLAN.sections[i],ws=c.vo.split(/\s+/);p.words=ws.map((w,j)=>({w,t0:p.voStart+j*(p.dur-.6)/ws.length,t1:p.voStart+(j+1)*(p.dur-.6)/ws.length}));});});await page.addScriptTag({path:dir+'/story.js'});
 const caption=async t=>{await page.evaluate(t=>{__timelines['mint-bento-programming'].seek(t,false)},t);return page.evaluate(()=>[...document.querySelectorAll('.caption')].filter(e=>getComputedStyle(e).visibility==='visible').map(e=>({text:e.textContent,active:[...e.children].filter(e=>getComputedStyle(e).backgroundColor==='rgb(189, 247, 223)').length})));};const t=sections[1].voStart+.02,cap=await caption(t);assert.equal(cap.length,1);assert.equal(cap[0].active,1);await caption(sections[3].voStart+.2);assert.deepEqual(await caption(t),cap);await page.screenshot({path:dir+'/qa/synthetic-caption.png'});
 await page.goto('file://'+dir+'/style-study.html');await page.evaluate(()=>document.fonts.ready);await page.setViewport({width:1200,height:800});await page.screenshot({path:dir+'/qa/style-sheet.png',fullPage:true});assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'pass',checks:['append preserves order','list and count commit together','proxy not counted in flight','same state across detail view','reverse seeks','horizontal text overflow','synthetic caption highlighting'],errors},null,2));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
