const fs=require('fs'),path=require('path'),assert=require('assert'),puppeteer=require('puppeteer-core'),sharp=require('sharp');
(async()=>{const dir=path.resolve(__dirname,'..'),browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-sandbox','--allow-file-access-from-files']}),page=await browser.newPage();await page.setViewport({width:1080,height:1920});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+dir+'/index.html');await page.evaluate(()=>document.fonts.ready);if(errors.length)throw Error(errors.join('\n'));const plan=await page.evaluate(()=>PLAN),ops=await page.evaluate(()=>OPERATION_SAMPLES),reveals=await page.evaluate(()=>REVEAL_SAMPLES);fs.mkdirSync(dir+'/snapshots',{recursive:true});
const seek=t=>page.evaluate(t=>{StoryTimeline.seek(t,false);},t);
const issues=[];async function inspect(t,label){await seek(t);const r=await page.evaluate(()=>{const visible=n=>{for(let a=n;a&&a.nodeType===1;a=a.parentElement){const s=getComputedStyle(a);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.85)return false;}return true;};return [...document.querySelectorAll('.copy,.code-unit,.signature,.line,.chrome,.tag,.role,.diff-row,.receipt,.caption-line,.trace-strip')].filter(visible).flatMap(n=>{const b=n.getBoundingClientRect(),why=[];if(n.scrollWidth>n.clientWidth+3||n.scrollHeight>n.clientHeight+3)why.push('overflow');if(b.left<-10||b.right>1090||b.top<0||b.bottom>1860&&n.className!=='caption-line')why.push('outside');return why.length?[{id:n.id,cls:n.className,text:n.textContent,why,rect:[b.x,b.y,b.width,b.height],scroll:[n.clientWidth,n.clientHeight,n.scrollWidth,n.scrollHeight]}]:[];});});if(r.length)issues.push({t,label,issues:r});}
for(let i=0;i<plan.sections.length;i++){const s=plan.sections[i];await inspect(s.start+s.dur-.4,'section '+i);await page.screenshot({path:dir+'/snapshots/section-'+String(i).padStart(2,'0')+'.png'});}
for(let i=0;i<ops.length;i++){const op=ops[i];if(!['model','reframe'].includes(op.kind))continue;for(const [tag,t] of [['before',op.start-.06],['mid',(op.start+op.end)/2],['after',op.end+.05]]){if(t<0||t>=plan.total)continue;await inspect(t,'op '+i+' '+op.job+' '+tag);if(op.kind==='model')await page.screenshot({path:dir+'/snapshots/op-'+i+'-'+tag+'.png'});}}
const leaks=[];for(const r of reveals){if(r.t<.1)continue;await seek(r.t+.8);await seek(r.t-.06);const bad=await page.evaluate(id=>{for(let n=document.getElementById(id);n&&n.nodeType===1;n=n.parentElement){const s=getComputedStyle(n);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.01)return false;}return true;},r.id);if(bad)leaks.push(r);}
for(const i of [12,2,10,7,4,13,0,12]){await inspect(plan.sections[i].start+plan.sections[i].dur-.4,'reverse '+i);const amount=await page.$eval('#paper .paper-amount',n=>n.textContent);assert.equal(amount,i<10?'100.000 đ':'90.000 đ');const title=await page.$eval('#paper .paper-title',n=>n.textContent);assert.equal(title,i<12?'HÓA ĐƠN':'PHIẾU\nTHANH TOÁN');}
for(let k=0;k<3;k++){const imgs=[];for(let j=0;j<5;j++)imgs.push({input:await sharp(`${dir}/snapshots/section-${String(k*5+j).padStart(2,'0')}.png`).resize(270,480).png().toBuffer(),left:j*270,top:0});await sharp({create:{width:1350,height:480,channels:3,background:'#050505'}}).composite(imgs).jpeg({quality:90}).toFile(`${dir}/snapshots/sheet-${k}.jpg`);}
// Gaps are time intervals, not op counts. Reframing and text do not clear a model gap.
const gaps=[];for(let i=0;i<plan.sections.length;i++){const s=plan.sections[i],spans=ops.filter(o=>o.kind==='model'&&o.end>s.start&&o.start<s.start+s.dur).sort((a,b)=>a.start-b.start);let end=s.start;for(const o of spans){if(o.start-end>3)gaps.push({section:i,start:end,end:o.start,duration:o.start-end});end=Math.max(end,o.end);}if(s.start+s.dur-end>3)gaps.push({section:i,start:end,end:s.start+s.dur,duration:s.start+s.dur-end});}
fs.writeFileSync(dir+'/custom-motion-review.json',JSON.stringify({ops,reveals,issues,leaks,errors,modelGapsOver3Seconds:gaps,scope:'model gaps exclude reframe/disclosure/chrome/attention; inspect all gaps, counts are not quality scores'},null,2));console.log(JSON.stringify({errors,issues:issues.slice(0,20),issueSamples:issues.length,leaks,modelGaps:gaps},null,2));await browser.close();if(issues.length||errors.length||leaks.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
