"""Turn script.json + timings.json into a timed plan and wire the audio into index.html.

- Section length = max(minimum, narration + tail). A section without narration lasts long enough to read its screen
  text (≈ 5 syllables/s + 2.5 s of entrance animation, scene 7–11 s, outro 6–9 s).
- Writes <project>/project-data.js: window.SCRIPT (content) + window.PLAN (starts, durations, words).
- Rewrites the block between <!-- AUDIO:BEGIN --> and <!-- AUDIO:END --> in index.html with one
  <audio> per narration clip + the BGM bed, and sets data-duration on #root and #explainer.
- Music bed, first found: --bgm <file> (the user's own track), assets/audio/bgm-source.*, assets/audio/bgm-default.*
  (shipped with the skill). It is cut/faded/normalized to assets/audio/bgm.m4a (needs ffmpeg). --no-bgm: none.
- The theme's intro sound (THEME.sfx: {file, at, volume}) gets its own <audio> tag timed with the intro animation.
- Music-only video (no voice, no captions): --music-only, or simply no timings.json. A voiced project can switch back
  and forth: --music-only ignores timings.json without deleting it.

Usage: python sync-narration.py --project <dir> [--music-only] [--bgm <file> | --no-bgm] [--bgm-volume 0.18]
"""
import argparse
import sys
import glob
import json
import pathlib
import re
import shutil
import subprocess

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import voice_common as vc  # noqa: E402
from word_timing import validate_words

LEAD = 0.15  # begin speech during the entrance, rather than waiting for it
TAIL = 0.35  # brief boundary spacing; a result is usually read during speech
MIN = {"intro": 2.2, "scene": 1.0, "outro": 2.2}  # minimum for entrance animation only


def section_duration(section_kind, narration, hold, screen):
    """Preserve all speech; explicit holds and short entrance floors are the only extras."""
    return max(MIN[section_kind], LEAD + narration + TAIL + hold) if narration else screen + hold


def media_seconds(path):
    """Real length of an audio file (ffprobe); None if it can't be read."""
    try:
        out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(path)],
                             capture_output=True, text=True, check=True).stdout.strip()
        return float(out)
    except (subprocess.CalledProcessError, ValueError, FileNotFoundError):
        return None


def theme_runtime(proj):
    """window.THEME from the project's theme.js (written by the skill build); {} if missing."""
    p = proj / "theme.js"
    m = re.search(r"window\.THEME\s*=\s*(\{.*\});", p.read_text(encoding="utf8"), re.S) if p.exists() else None
    return json.loads(m.group(1)) if m else {}


def kind(sid):
    return "intro" if sid == "intro" else "outro" if sid == "outro" else "scene"


def main():
    # Windows consoles default to cp1252; Vietnamese output would crash print().
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--bgm-volume", type=float, default=0.18)
    ap.add_argument("--bgm", help="path to the user's own music file (any format ffmpeg reads)")
    ap.add_argument("--no-bgm", action="store_true")
    ap.add_argument("--music-only", action="store_true", help="no voice, no captions (ignores timings.json)")
    args = ap.parse_args()
    proj = pathlib.Path(args.project)
    script = json.loads((proj / "script.json").read_text(encoding="utf-8-sig"))
    tpath = proj / "timings.json"
    voiced = tpath.exists() and not args.music_only
    timings = json.loads(tpath.read_text(encoding="utf8")) if voiced else {"sections": []}
    screen = vc.screen_seconds(script)
    by_id = {s["id"]: s for s in timings["sections"]}
    order = ["intro"] + [f"scene-{i + 1}" for i in range(len(script["scenes"]))] + ["outro"]

    plan, t = [], 0.0
    for sid in order:
        k = kind(sid)
        tm = by_id.get(sid, {})
        vo = tm.get("duration") or 0.0
        content = script[sid] if sid in {"intro", "outro"} else script["scenes"][int(sid.split("-")[1])-1]
        hold = float(content.get("hold", 0))
        dur = section_duration(k, vo, hold, screen[sid])
        if tm.get('words'):
            validate_words(tm['words'], vo)
        words = [{"w": w["w"], "t0": round(t + LEAD + w["start"], 3), "t1": round(t + LEAD + w["end"], 3)}
                 for w in tm.get("words", [])]
        plan.append({"id": sid, "start": round(t, 3), "dur": round(dur, 3), "file": tm.get("file"),
                     "voStart": round(t + LEAD, 3), "voDur": vo, "words": words})
        t += dur
    total = round(t, 2)

    data = "// Generated by sync-narration.py. Edit script.json, then re-run tts + sync.\n"
    data += "window.SCRIPT = " + json.dumps(script, ensure_ascii=False, indent=1) + ";\n"
    data += "window.PLAN = " + json.dumps({"total": total, "sections": plan}, ensure_ascii=False) + ";\n"
    (proj / "project-data.js").write_text(data, encoding="utf8")

    # Music bed cut (looped if shorter) to the exact total length.
    adir = proj / "assets" / "audio"
    src = [args.bgm] if args.bgm else (sorted(glob.glob(str(adir / "bgm-source.*"))) or sorted(glob.glob(str(adir / "bgm-default.*"))))
    if args.bgm and not pathlib.Path(args.bgm).exists():
        sys.exit(f"--bgm file not found: {args.bgm}")
    has_bgm = (adir / "bgm.m4a").exists() and not args.no_bgm
    if src and not args.no_bgm:
        adir.mkdir(parents=True, exist_ok=True)
        fade = max(0.0, total - 2.0)
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-stream_loop", "-1", "-ss", "0", "-t", str(total), "-i", src[0], "-af",
                        f"afade=t=in:d=0.3,afade=t=out:st={fade}:d=2,loudnorm=I=-17:TP=-1.5:LRA=11",
                        "-ar", "48000", "-c:a", "aac", "-b:a", "192k", str(adir / "bgm.m4a")],
                       check=True)
        has_bgm = True

    tags = []
    if has_bgm:
        tags.append(f'<audio id="bgm" src="assets/audio/bgm.m4a" data-start="0" data-duration="{total}" '
                    f'data-track-index="2" data-volume="{args.bgm_volume}"></audio>')
    # The theme's intro sound (THEME.sfx in theme.js), placed on the intro's stretched clock like its animation.
    sfx = theme_runtime(proj).get("sfx")
    if sfx and (proj / sfx["file"]).exists():
        intro = plan[0]
        at = round(intro["start"] + sfx["at"] * min(1.7, max(0.8, intro["dur"] / 7)), 3)
        real = media_seconds(proj / sfx["file"]) or 1.0
        tags.append(f'<audio id="sfx-intro" src="{sfx["file"]}" data-start="{at}" data-duration="{int(real * 1000) / 1000}" '
                    f'data-track-index="5" data-volume="{sfx.get("volume", 0.6)}"></audio>')
    for n, s in enumerate(plan):
        if s["file"]:
            # Slot = spoken length + 0.3s, never longer than the file itself (avoids clip_media_fit warnings).
            real = media_seconds(proj / s["file"])
            slot = s["voDur"] + 0.3 if real is None else min(s["voDur"] + 0.3, int(real * 1000) / 1000)
            tags.append(f'<audio id="vo-{n:02d}" src="{s["file"]}" data-start="{s["voStart"]}" '
                        f'data-duration="{round(slot, 3)}" data-track-index="{3 + n % 2}" data-volume="1"></audio>')

    ipath = proj / "index.html"
    html = ipath.read_text(encoding="utf8")
    block = "<!-- AUDIO:BEGIN -->\n      " + "\n      ".join(tags) + "\n      <!-- AUDIO:END -->"
    html = re.sub(r"<!-- AUDIO:BEGIN -->.*?<!-- AUDIO:END -->", lambda m: block, html, flags=re.S)
    html = re.sub(r'(id="root"[^>]*?data-duration=")[0-9.]+(")', rf"\g<1>{total}\g<2>", html)
    html = re.sub(r'(id="explainer"[^>]*?data-duration=")[0-9.]+(")', rf"\g<1>{total}\g<2>", html)
    ipath.write_text(html, encoding="utf8")

    if voiced:
        overhead = sum(s["dur"] - s["voDur"] for s in plan if s["voDur"])
        print(f"Spacing outside voiced clips: {overhead:.2f}s (includes explicit holds/entrance floors)")
    for s in plan:
        print(f'{s["id"]:<9} start {s["start"]:6.2f}  dur {s["dur"]:5.2f}  vo {s["voDur"]:5.2f}')
    print(f"total {total}s · audio tags {len(tags)} · bgm {'yes' if has_bgm else 'no'} · "
          f"{'voice + captions' if voiced else 'music only (no voice, no captions)'}")
    shutil.rmtree(proj / "snapshots", ignore_errors=True)  # timings changed: old snapshots are stale
    shots = [3, 5] + [round(s["start"] + s["dur"] - 1.0, 1) for s in plan]
    print("snapshot: npx hyperframes snapshot --at " + ",".join(str(x) for x in shots))


if __name__ == "__main__":
    main()
