/* Checks this shipped remainder fixture, not arbitrary future productions. */
const fs=require('fs'),path=require('path'),assert=require('assert'),puppeteer=require('puppeteer-core');
(async()=>{const [project,chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']=process.argv.slice(2);const dir=path.resolve(project);const browser=await puppeteer.launch({executablePath:chrome,headless:true,args:['--no-sandbox','--allow-file-access-from-files']});try{
 const page=await browser.newPage();await page.setViewport({width:1080,height:1920});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+dir+'/index.html');await page.evaluate(()=>document.fonts.ready);assert.deepEqual(errors,[]);await page.waitForFunction(()=>!!window.__timelines?.['bauhaus-programming']);
 const sections=await page.evaluate(()=>PLAN.sections);const state=async t=>{await page.evaluate(t=>{__timelines['bauhaus-programming'].seek(t,false)},t);return page.evaluate(()=>{const visible=e=>{for(let n=e;n instanceof Element;n=n.parentElement){const s=getComputedStyle(n);if(s.display==='none'||s.visibility==='hidden'||+s.opacity===0)return false;}return true;};const page=[...document.querySelectorAll('.page')].find(visible);return {page:page?.dataset.section,dots:[...page.querySelectorAll('[data-dot]')].filter(visible).map(e=>{const b=e.getBoundingClientRect();return [e.dataset.dot,+b.x.toFixed(2),+b.y.toFixed(2)];}),result:[...page.querySelectorAll('[data-result]')].filter(visible).map(e=>e.textContent)};});};
 fs.mkdirSync(dir+'/qa',{recursive:true});const expected={};const firstCue=await page.evaluate(()=>Bauhaus.cue(SCRIPT.scenes[0],PLAN.sections[1],'first'));const times=[.1,firstCue-.05,firstCue+.3,firstCue+.8,...sections.map(p=>p.start+p.dur-.4)];for(const t of times){expected[t]=await state(t);await page.screenshot({path:dir+'/qa/t-'+t.toFixed(2)+'.png'});}
 for(let i=1;i<=3;i++){const p=sections[i];const st=expected[p.start+p.dur-.4];assert.equal(st.dots.length,i+6);assert.deepEqual(st.result,[`${i+6} % 3 = ${(i+6)%3}`]);
  const resultTime=await page.evaluate(i=>Bauhaus.cue(SCRIPT.scenes[i-1],PLAN.sections[i],'result'),i);assert.deepEqual((await state(resultTime-.05)).result,[]);assert.equal((await state(resultTime+.35)).result.length,1);}
 for(const t of [...times].reverse().concat(times))assert.deepEqual(await state(t),expected[t],'history independent seek '+t);
 const last=expected[sections[3].start+sections[3].dur-.4];assert(last.dots.slice(6).every(d=>d[1]<500),'third group must move out of remainder region');
 const overflow=[];for(const p of sections){await state(p.start+p.dur-.4);overflow.push(...await page.evaluate(()=>[...document.querySelectorAll('.page')].filter(p=>getComputedStyle(p).display!=='none').flatMap(p=>[...p.querySelectorAll('.placed')].filter(e=>e.scrollWidth>e.clientWidth+3).map(e=>e.textContent))));}assert.deepEqual(overflow,[]);
 // Synthetic word times exercise caption rendering only; these are not TTS/alignment evidence.
 await page.evaluate(()=>{__timelines['bauhaus-programming'].kill();document.getElementById('pages').replaceChildren();document.getElementById('captions').replaceChildren();const cs=[SCRIPT.intro,...SCRIPT.scenes,SCRIPT.outro];PLAN.sections.forEach((p,i)=>{const ws=cs[i].vo.split(/\s+/);p.words=ws.map((w,j)=>({w,t0:p.voStart+j*(p.dur-.6)/ws.length,t1:p.voStart+(j+1)*(p.dur-.6)/ws.length}));});});
 await page.addScriptTag({path:dir+'/story.js'});
 const capState=async t=>{await page.evaluate(t=>{__timelines['bauhaus-programming'].seek(t,false)},t);return page.evaluate(()=>[...document.querySelectorAll('.caption')].filter(e=>getComputedStyle(e).visibility==='visible').map(e=>({text:e.textContent,active:[...e.children].filter(x=>getComputedStyle(x).backgroundColor==='rgb(254, 178, 26)').length})));};
 const capTime=sections[1].voStart+.02,cs=await capState(capTime);assert.equal(cs.length,1);assert.equal(cs[0].active,1);await capState(sections[3].voStart+.2);assert.deepEqual(await capState(capTime),cs);await page.screenshot({path:dir+'/qa/synthetic-caption.png'});
 await page.goto('file://'+dir+'/style-study.html');await page.evaluate(()=>document.fonts.ready);await page.setViewport({width:1200,height:1410});await page.screenshot({path:dir+'/qa/style-sheet.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'pass',checks:['7/8/9 item conservation','remainder 1/2/0','result hidden until cue','third group leaves empty remainder','backward seeking','horizontal text overflow','synthetic caption highlighting and reverse seek'],timing:'silent estimated unless synced voice was supplied',errors},null,2));
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
