function initSrpStory(){'use strict';
const P=window.PLAN,S=window.SCORE,tl=gsap.timeline({paused:true}),D=document.getElementById('srp-diagram'),O=document.getElementById('srp-foreground'),OPS=[],REV=[];let id=0;
const C={a:'#D97757',v:'#C4B5FD',b:'#93C5FD',g:'#86EFAC'};
function E(cls,parent=D,content){const n=document.createElement('div');n.id='e'+(++id);n.className=cls;if(content!=null)n.textContent=content;parent.appendChild(n);return n;}
function box(n,x,y,w,h){Object.assign(n.style,{left:x+'px',top:y+'px',width:w+'px',...(h?{height:h+'px'}:{})});return n;}
function tx(parent,str,x,y,w,size=36,cls=''){const n=box(E('copy '+cls,parent,str),x,y,w);n.style.fontSize=size+'px';return n;}
const norm=s=>String(s).toLowerCase().normalize('NFC').match(/[\p{L}\p{N}]+/gu)||[];
function cue(i,phrase){const key=norm(typeof phrase==='number'?S[i].cues[phrase]:phrase),ws=P.sections[i].words.flatMap(w=>norm(w.w).map(v=>({v,t:w.t0})));const j=ws.findIndex((_,j)=>key.every((v,k)=>ws[j+k]?.v===v));if(j<0)throw Error('cue '+i+' '+phrase);return ws[j].t;}
const st=i=>P.sections[i].start,en=i=>st(i)+P.sections[i].dur;
function record(n,t,d,kind,job){OPS.push({id:n.id,start:t,end:t+d,kind,job});}
function show(n,t,d=.45,job='disclose'){gsap.set(n,{autoAlpha:0,display:'none'});tl.set(n,{display:'block',visibility:'visible'},t);tl.to(n,{opacity:1,duration:d},t);REV.push({id:n.id,t});record(n,t,d,'disclosure',job);}
function appear(n,t,d=.35){tl.set(n,{display:'block',visibility:'visible'},t);tl.to(n,{opacity:1,duration:d},t);}
function hide(n,t,d=.25){tl.to(n,{opacity:0,duration:d},t);tl.set(n,{display:'none',visibility:'hidden'},t+d);}
function move(n,vars,t,d=.8,job='inspect',kind='reframe'){tl.to(n,{...vars,duration:d,ease:'power2.inOut'},t);record(n,t,d,kind,job);}
const prev=new Map();function write(n,s,t,job,kind='model'){let before=prev.has(n)?prev.get(n):n.textContent;tl.fromTo(n,{textContent:before},{textContent:s,duration:0,immediateRender:false},t);prev.set(n,s);record(n,t,.02,kind,job||'state commit');}
function path(g,d,t,col=C.a,job='connect',dur=.65,kind='model'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('route-svg');g.appendChild(svg);const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',d);p.setAttribute('stroke',col);svg.appendChild(p);const len=p.getTotalLength();gsap.set(p,{strokeDasharray:len,strokeDashoffset:len});tl.to(p,{strokeDashoffset:0,duration:dur,ease:'power2.inOut'},t);record(g,t,dur,kind,job);return svg;}
function token(g,label,x,y,xx,yy,t,d=.9,col=C.a){const n=box(E('token',g,label),x,y,0);n.style.width='auto';n.style.setProperty('--role',col);show(n,t,.05);move(n,{left:xx,top:yy},t,d,'transfer '+label,'model');hide(n,t+d,.12);return n;}
const scenes=P.sections.map((s,i)=>{const n=E('shot',O);n.id='shot-'+i;tl.set(n,{display:'block',visibility:'visible'},s.start);tl.set(n,{display:'none',visibility:'hidden'},s.start+s.dur);write(document.getElementById('counter'),String(i+1).padStart(2,'0')+' / 15',s.start,'counter','chrome');return n;});
const labels=['MỘT THAY ĐỔI NHỎ','MỞ TỆP MÃ','THEO DÕI HAI HÀM','NGƯỜI YÊU CẦU / 01','NGƯỜI YÊU CẦU / 02','SINGLE RESPONSIBILITY','TÁCH MÃ / 01','TÁCH MÃ / 02','CHẠY HÓA ĐƠN','BẢN SỬA / GIẢM GIÁ','KIỂM CHỨNG KẾT QUẢ','BẢN SỬA / TIÊU ĐỀ','SO SÁNH CÙNG DỮ LIỆU','MỘT TRÁCH NHIỆM','GHI NHỚ TỪ VÍ DỤ'];
labels.forEach((x,i)=>write(document.getElementById('phase'),String(i+1).padStart(2,'0')+' /// '+x,st(i),'context','chrome'));
function title(i,parts,x=64,y=225,w=952,size=86,t=st(i)+.1){const n=tx(scenes[i],'',x,y,w,size,'display heading');parts.forEach(([s,cls])=>{const sp=document.createElement('span');sp.textContent=s;sp.className=cls||'';n.appendChild(sp);});show(n,t);return n;}
function tag(i,s,x,y,t,col=C.a){const n=box(E('tag',scenes[i],s),x,y,0);n.style.width='auto';n.style.color=col;show(n,t);return n;}
function role(i,name,ask,x,y,w,t,col=C.a,sign='↗'){const n=box(E('role',scenes[i]),x,y,w,236);n.style.setProperty('--role',col);n.style.setProperty('--tint',col+'22');E('disc',n,sign);E('who',n,name);E('ask',n,ask);show(n,t);return n;}
function receipt(id,x,y,w,h){const n=box(E('receipt'),x,y,w,h);n.id=id;E('paper-top',n,'INVOICE / 001');const title=E('paper-title',n,'HÓA ĐƠN'),items=E('items',n,'40.000 + 30.000 × 2'),amount=E('paper-amount',n,'100.000 đ');E('paper-label',n,'TỔNG PHẢI TRẢ');return {root:n,title,items,amount};}
function term(id,label,x,y,w,h){const n=box(E('term'),x,y,w,h);n.id=id;const name=E('chrome',n,label);return {root:n,name};}
function unit(id,name,lines,x,y,w,col){const n=box(E('code-unit'),x,y,w,200);n.id=id;n.style.setProperty('--role',col);const sig=E('signature',n,name),fields=lines.map((line,j)=>{const row=E('line',n);row.dataset.ln=String(j+1).padStart(2,'0');const v=document.createElement('span');v.className='v';v.id=id+'-value-'+j;v.textContent=line;row.appendChild(v);return {row,v};});return {root:n,sig,fields};}
const file=term('invoice-owner','invoice.py / Invoice',245,1030,740,500),calc=unit('calc','total()', ['subtotal = 100_000','discount = 0%','total = 100_000'],285,1130,660,C.a),view=unit('presenter','render()', ['title = "HÓA ĐƠN"','print(title, total)'],285,1380,660,C.v);
const data=box(E('tag',D,'40.000 + 30.000 × 2'),96,620,570,70);data.id='invoice-data';const cf=term('calculator-file','calculator.py / InvoiceCalculator',64,545,952,420),vf=term('presenter-file','presenter.py / InvoicePresenter',64,1100,952,440);const paper=receipt('paper',150,735,665,540);
// 00. A receipt is the subject; an actual title selection leads into its shared source.
{const i=0,g=scenes[i];title(i,[['Đổi mẫu in.\n'],['Mở cả lớp\ntính tiền?','accent']],64,210,950,116,cue(i,0));show(paper.root,cue(i,0));gsap.set(paper.root,{rotation:3});const q=box(E('stamp',g,'?'),120,705,64,64);show(q,cue(i,0)+.3);const sel=box(E('border-only',g),170,830,600,105);sel.style.borderColor=C.v;show(sel,cue(i,0)+.45);move(paper.root,{left:64,top:875,width:410,height:470,rotation:-3},cue(i,1),.8,'inspect printed title');tl.to([paper.title,paper.amount],{fontSize:34,duration:.8},cue(i,1));hide(sel,cue(i,1));move(q,{left:42,top:842},cue(i,1),.8,'question follows inspected print','attention');show(file.root,cue(i,1)+.1);gsap.set(file.root,{rotation:-2});show(calc.root,cue(i,1)+.4);show(view.root,cue(i,1)+.65);gsap.set([calc.root,view.root],{zIndex:4});move(file.root,{left:480,top:875,width:536,height:700},cue(i,1),.8);move(calc.root,{left:515,top:990,width:466,height:245},cue(i,1),.8);move(view.root,{left:515,top:1290,width:466,height:220},cue(i,1),.8);path(g,'M380 860 H780 V910',cue(i,1),C.v,'receipt title resolves to shared file');tag(i,'2 yêu cầu → cùng tệp mã',110,1580,cue(i,2));path(g,'M498 1012 H487 V1540 H995 V1295',cue(i,2),C.v,'one source file contains both change targets',.9);}
// 01. Data and methods assemble INSIDE the class boundary, in spoken order.
{const i=1,g=scenes[i];hide(paper.root,st(i));title(i,[['Bên trong\n'],['Invoice','accent']],64,215,700,104);move(file.root,{left:64,top:565,width:952,height:1050,rotation:0},st(i),.8);move(calc.root,{left:106,top:890,width:868,height:270},st(i),.8);move(view.root,{left:106,top:1260,width:868,height:245},st(i),.8);hide(calc.root,st(i));hide(view.root,st(i));show(data,cue(i,1));move(data,{left:105,top:700,width:650},cue(i,1),.7,'place shared data under owner','model');appear(calc.root,cue(i,2)-.6);appear(view.root,cue(i,2)+.2);path(g,'M945 858 H984 V1518 H945',cue(i,2),C.v,'enclose two methods inside Invoice',.85);tag(i,'dữ liệu + hàm',96,1535,cue(i,2)+.2,C.b);}
// 02. The functions actually calculate and compose output. No static pair with changing headlines.
{const i=2,g=scenes[i];title(i,[['Hai hàm.\n'],['Hai phần việc.','italic']],64,210,950,90);move(file.root,{left:64,top:550,width:952,height:1070},st(i));move(data,{left:104,top:680},st(i));move(calc.root,{left:104,top:825,width:868,height:260},st(i));move(view.root,{left:104,top:1190,width:868,height:245},st(i));const c=cue(i,0);token(g,'40.000 + 60.000',390,695,390,1010,c,.9,C.b);const result=tag(i,'100.000 đ',590,1085,c+.9);record(result,c+.9,.1,'model','calculation materializes result');move(result,{left:590,top:1340},cue(i,1),.9,'computed total enters presentation','model');hide(result,cue(i,1)+.95);const mini=box(E('receipt',g),630,1440,320,170);E('paper-top',mini,'HÓA ĐƠN');const val=E('copy',mini,'100.000 đ');Object.assign(val.style,{fontSize:'37px',top:'75px'});show(mini,cue(i,1)+.9);record(mini,cue(i,1)+.9,.45,'model','presenter composes print output');path(g,'M990 820 H1004 V1460 H990',cue(i,'Hai hàm cùng nằm'),C.v,'group the two demonstrated operations under one class',.8);const ask=tx(g,'Ai yêu cầu chúng đổi?',64,425,950,42,'muted');show(ask,cue(i,2));}
// 03–04. Two requests land on different lines of the SAME FILE. Patches remain proposals.
function requestShot(i,which){const g=scenes[i],t=cue(i,0),col=which?C.v:C.a;hide(data,st(i));move(file.root,{left:346,top:810,width:670,height:870,rotation:which?1.4:-1.4},st(i));move(calc.root,{left:380,top:910,width:600,height:245},st(i));move(view.root,{left:380,top:1270,width:600,height:225},st(i));title(i,which?[['Một nơi.\n'],['Hai lý do.','violet']]:[['Ai làm\n'],['mã thay đổi?','accent']],64,210,950,108);role(i,which?'Vận hành':'Kinh doanh',which?'Đổi tiêu đề bản in':'Đổi mức giảm giá',64,540,470,t,col,which?'Aa':'%');const yy=which?1320:1005;path(g,`M215 782 V${yy} H365`,cue(i,1)-.15,col,'route change request into exact method',.8);token(g,which?'Δ tiêu đề':'Δ giảm giá',92,800,88,yy+70,cue(i,1),.9,col);const patch=box(E('diff',g),100,which?1550:1170,780,90);const r=E('diff-row new',patch,which?'? title = yêu cầu mới':'? discount = yêu cầu mới');r.style.color=col;show(patch,cue(i,1)+.9);record(patch,cue(i,1)+.9,.3,'model','attach pending patch to its owning code');tag(i,'CHƯA ÁP DỤNG',64,1640,cue(i,1)+.9,col);if(which){const a=tag(i,'KINH DOANH',64,890,cue(i,2),C.a);path(g,'M210 957 V1035 H364',cue(i,2)+.3,C.a,'show second request still targets same owner');}else{const witness=tx(g,'Mẫu in\ngiữ nguyên',64,1375,290,42,'display');show(witness,cue(i,2));path(g,'M215 1485 H365',cue(i,2),C.v,'inspect unchanged render method');}}
requestShot(3,false);requestShot(4,true);
// 05. Name the rule while known requests build the observed two-to-one relationship.
{const i=5,g=scenes[i];hide(file.root,st(i));hide(calc.root,st(i));hide(view.root,st(i));const orb=box(E('orb',g),620,265,290,390);show(orb,st(i),.1);title(i,[['S','accent']],64,210,350,220,cue(i,0));const name=tx(g,'SINGLE\nRESPONSIBILITY\nPRINCIPLE',420,300,620,34,'mono');show(name,cue(i,0));title(i,[['Một lý do\n'],['để thay đổi.','accent']],64,610,950,100,cue(i,1));const owner=box(E('term',g),64,1190,952,435);E('chrome',owner,'Invoice / mô đun đang xét');show(owner,cue(i,'Một mô đun'));const a=box(E('trace-strip',g,'total()'),100,1330,398,160),b=box(E('trace-strip',g,'render()'),575,1330,398,160);b.style.setProperty('--role',C.v);show(a,cue(i,'Một mô đun'));show(b,cue(i,'Một mô đun')+.25);path(g,'M83 1290 V1530 H991 V1290',cue(i,'Một mô đun'),C.a,'the known operations share one module boundary',.8);const sales=tag(i,'KINH DOANH',94,1020,cue(i,'phục vụ'),C.a);path(g,'M245 1080 V1320',cue(i,'một nhóm nhu cầu'),C.a,'first cohesive change source reaches total',.8);const ops=tag(i,'VẬN HÀNH',600,1020,cue(i,'hai nhóm'),C.v);path(g,'M760 1080 V1320',cue(i,'hai nhóm'),C.v,'independent second change source reaches render',.85);tag(i,'2 lý do trong 1 nơi',330,1540,cue(i,2),C.v);}
// 06–07. Original strips leave the old file; new file boundaries form AROUND existing code.
{const i=6,g=scenes[i];title(i,[['Tách mã,\n'],['giữ phần việc.','accent']],64,210,940,96);appear(file.root,st(i));move(file.root,{left:64,top:760,width:952,height:870,rotation:0},st(i),.6);appear(calc.root,st(i));appear(view.root,st(i));move(calc.root,{left:104,top:850,width:868,height:245},st(i),.6);move(view.root,{left:104,top:1290,width:868,height:235},st(i),.6);appear(data,cue(i,1));move(data,{left:64,top:510,width:670},cue(i,1),.7,'shared data stays outside split','model');const t=cue(i,2);move(calc.root,{left:105,top:720,width:868,height:245},t,.95,'extract total method from Invoice','model');move(file.root,{top:1110,height:520},t,.95,'remaining source owner');hide(file.name,t,.1);appear(file.name,t+.95);show(cf.root,t+.15);move(cf.root,{top:630,height:385},t,.8,'new boundary owns extracted method','model');tl.set(cf.root,{zIndex:0},0);write(calc.sig,'total()  /  tính tiền',t+.95,'preserve method in Calculator','disclosure');const tab=box(E('file-tab',g),64,594,0);tab.style.width='auto';tab.textContent='01 / calculator.py';show(tab,t+.4);}
{const i=7,g=scenes[i];title(i,[['Phần trình bày\n'],['có nơi riêng.','violet']],64,210,952,85);const t=cue(i,0),owned=cue(i,2);hide(file.name,t,.1);gsap.set(vf.root,{height:0});show(vf.root,owned-.15);tl.set(vf.root,{zIndex:0},0);move(vf.root,{left:64,top:1130,width:952,height:485},owned-.15,.8,'assign extracted render to new Presenter boundary','model');move(file.root,{left:750,top:1600,width:265,height:70},t,.8,'old source becomes empty after last extraction','model');move(view.root,{left:105,top:1240,width:868,height:230},t,.85,'extract render method from Invoice','model');hide(file.root,owned+.2);write(view.sig,'render()  /  bản in',t+.85,'preserve method in Presenter','disclosure');const a=tag(i,'total() giữ nguyên',400,1025,cue(i,1),C.a),b=tag(i,'render() giữ nguyên',400,1505,cue(i,1)+.25,C.v);path(g,'M82 710 V966 M82 1230 V1460',cue(i,2),C.v,'inspect distinct ownership boundaries',.65,'attention');}
// 08. Execution rail with actual value handoffs and a printable output, not three process bullets.
{const i=8,g=scenes[i];hide(cf.root,st(i));hide(vf.root,st(i));hide(calc.root,st(i));hide(view.root,st(i));hide(data,st(i));title(i,[['Tách trách nhiệm.\n'],['Vẫn phối hợp.','italic']],64,220,950,87);const spine=box(E('rail',g),103,600,4,785);show(spine,st(i));const positions=[595,900,1205];positions.forEach((y,j)=>{const n=box(E('step',g,String(j+1)),74,y,60,60);show(n,st(i));});const a=box(E('trace-strip',g,'DỮ LIỆU\n40.000 + 30.000 × 2'),176,575,820,190),b=box(E('trace-strip',g,'Calculator.total()\n100.000 đ'),176,885,820,190),c=box(E('trace-strip',g,'Presenter.render()'),176,1190,820,110);a.style.setProperty('--role',C.b);c.style.setProperty('--role',C.v);show(a,cue(i,0)-.4);token(g,'dữ liệu',405,700,405,925,cue(i,0),.85,C.b);show(b,cue(i,0)+.85);record(b,cue(i,0)+.85,.2,'model','calculator returns total');token(g,'100.000 đ',420,1000,420,1220,cue(i,1),.85);show(c,cue(i,1)+.8);move(paper.root,{left:545,top:1340,width:450,height:350,rotation:2},st(i),.1);tl.set(paper.items,{display:'none'},st(i));tl.set([paper.title,paper.amount],{fontSize:34},st(i));appear(paper.root,cue(i,2));tl.fromTo(paper.root,{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0 0 0% 0)',duration:.7,immediateRender:false},cue(i,2));record(paper.root,cue(i,2),.7,'model','compose printed result');path(g,'M103 655 V1480 H520',cue(i,3),C.v,'complete collaboration path',.8);const note=tx(g,'Dữ liệu đi qua.\nTrách nhiệm tách riêng.',65,1500,430,30,'muted');show(note,cue(i,3)+.1);}
// 09. A visible patch, then an exact source edit. A separate file remains unedited.
{const i=9,g=scenes[i];hide(paper.root,st(i));title(i,[['01'],[' / Đổi giảm giá','accent']],64,245,952,80);const r=role(i,'Kinh doanh','Yêu cầu chính sách giá',64,455,420,cue(i,0),C.a,'%');const diff=box(E('diff',g),540,455,475,240);E('diff-row old',diff,'− discount = 0%');const added=E('diff-row new',diff,'+ discount = 10%');gsap.set(added,{autoAlpha:0});show(diff,cue(i,0));path(g,'M489 575 H528',cue(i,'kinh doanh'),C.a,'pricing request reaches proposed patch',.6);tl.to(added,{autoAlpha:1,duration:.2},cue(i,1));record(added,cue(i,1),.2,'disclosure','proposed discount patch');appear(cf.root,st(i));move(cf.root,{left:64,top:850,width:952,height:490},st(i),.4);appear(calc.root,st(i));move(calc.root,{left:108,top:970,width:864,height:265},st(i),.4);const commit=cue(i,2)+.5;token(g,'discount = 10%',580,645,430,1080,commit-.85,.85);write(calc.fields[1].v,'discount = 10%',commit,'apply discount policy to Calculator');write(calc.fields[2].v,'total = ?',commit,'invalidate previous run after policy edit');const staticFile=box(E('term',g),540,1440,475,190);E('chrome',staticFile,'presenter.py');const note=tx(staticFile,'Không sửa mã',28,86,420,30,'violet');show(staticFile,cue(i,3));path(g,'M120 1375 H490',cue(i,3),C.a,'separate edited and unchanged file scopes');tag(i,'1 tệp được sửa',64,1460,cue(i,3),C.g);}
// 10. Subtract a real 10% segment, then send the committed amount into the unchanged presenter.
{const i=10,g=scenes[i];hide(cf.root,st(i));hide(calc.root,st(i));title(i,[['100.000'],[' × (1 − 10%)','accent']],64,235,952,68,cue(i,0));const full=box(E('bar',g),64,560,940,95),discount=box(E('bar',g),910,560,94,95);discount.style.background='#C4B5FD';show(full,cue(i,0));show(discount,cue(i,0));const ten=tx(g,'10.000',660,730,245,35,'mono violet');show(ten,cue(i,1)-.65);move(discount,{top:710},cue(i,1)-.65,.65,'subtract 10 percent segment','model');move(full,{width:846},cue(i,1)-.65,.65,'retain 90 percent of amount','model');const big=tx(g,'90.000',64,815,840,180,'display accent');show(big,cue(i,1));write(calc.fields[2].v,'total = 90_000',cue(i,1),'commit computed discounted total');const cmd=box(E('term',g),64,1180,952,195);E('chrome',cmd,'presenter.py / mã giữ nguyên');tx(cmd,'render(total)',34,85,880,45,'mono violet');show(cmd,cue(i,'Chạy lại'));token(g,'90.000 đ',740,1055,620,1270,cue(i,'Chạy lại'),.8);move(paper.root,{left:540,top:1385,width:460,height:315,rotation:0},st(i),.1);tl.set(paper.title,{fontSize:30},st(i));tl.set(paper.amount,{fontSize:43},st(i));appear(paper.root,cue(i,2));write(paper.amount,'90.000 đ',cue(i,2),'output receives new total without source edit');path(g,'M780 1380 V1410',cue(i,2),C.v,'presenter produces new data');const v=tx(g,'Dữ liệu mới.\nMã vẫn cũ.',64,1490,430,46,'display');show(v,cue(i,3));}
// 11. Second request opens the other file. Old and new title are local diff rows.
{const i=11,g=scenes[i];hide(paper.root,st(i));title(i,[['02'],[' / Đổi tiêu đề','violet']],64,245,952,80);role(i,'Vận hành','Yêu cầu bản in',64,450,420,cue(i,0),C.v,'Aa');const diff=box(E('diff',g),540,450,475,325);E('diff-row old',diff,'− HÓA ĐƠN');const newrow=E('diff-row new',diff,'+ PHIẾU\n  THANH TOÁN');gsap.set(newrow,{autoAlpha:0});show(diff,cue(i,0));path(g,'M489 570 H528',cue(i,0),C.v,'format request reaches proposed heading patch',.65);tl.to(newrow,{autoAlpha:1,duration:.2},cue(i,1));appear(vf.root,st(i));move(vf.root,{left:64,top:900,width:952,height:450},st(i),.5);appear(view.root,st(i));move(view.root,{left:104,top:1010,width:872,height:240},st(i),.5);const t=cue(i,2)+.55;token(g,'title',710,715,650,1140,t-.8,.8,C.v);write(view.fields[0].v,'title = "PHIẾU THANH TOÁN"',t,'apply heading patch to Presenter');tag(i,'calculator.py  ·  không sửa',64,1470,cue(i,3),C.a);const val=tx(g,'10%',700,1400,330,140,'display accent');show(val,cue(i,3));}
// 12. Rerun: current output and retained baseline align at the amount, differing at the title.
{const i=12,g=scenes[i];hide(vf.root,st(i));hide(view.root,st(i));title(i,[['Cùng dữ liệu.\n'],['Kiểm tra bản in.','italic']],64,210,950,88);const cmd=tag(i,'total() → render()',64,520,cue(i,0),C.v);token(g,'90.000',350,570,660,895,cue(i,0)+.1,.85);const before=box(E('receipt',g),64,850,440,620);E('paper-top',before,'TRƯỚC KHI ĐỔI TIÊU ĐỀ');const oldTitle=E('paper-title',before,'HÓA ĐƠN');oldTitle.style.minHeight='90px';E('items',before,'Giảm giá 10%\nCùng dữ liệu');E('paper-amount',before,'90.000 đ');E('paper-label',before,'TỔNG PHẢI TRẢ');show(before,cue(i,0));move(paper.root,{left:560,top:850,width:456,height:620,rotation:0},st(i),.1);tl.set(paper.items,{display:'block',textContent:'Giảm giá 10%\nCùng dữ liệu'},st(i));tl.set(paper.title,{fontSize:38,minHeight:90},st(i));tl.set(paper.amount,{fontSize:57},st(i));appear(paper.root,cue(i,0)+.85);write(paper.title,'PHIẾU\nTHANH TOÁN',cue(i,1),'commit changed print heading');const q=box(E('stamp',g,'✓'),950,815,64,64);show(q,cue(i,1));const rail=box(E('border-only',g),84,1185,910,148);rail.style.borderColor=C.g;show(rail,cue(i,2));path(g,'M512 1274 H548',cue(i,2),C.g,'compare unchanged amounts');const proof=tx(g,'Calculator       Presenter',64,1570,952,36,'mono');show(proof,cue(i,3));path(g,'M88 1290 H46 V1540 H250 M1024 1030 H1040 V1540 H795',cue(i,3),C.v,'map verified amount and title back to distinct source owners',.9);}
// 13. Strike the wrong counting rule; run three cohesive operations inside one class.
{const i=13,g=scenes[i];hide(paper.root,st(i));const myth=title(i,[['Một lớp = một hàm?']],64,225,952,80);const strike=box(E('bar',g),64,280,0,5);strike.style.background='#FCA5A5';show(strike,cue(i,0),.01);move(strike,{width:910},cue(i,0),.6,'reject method-count interpretation','attention');const bound=box(E('term',g),64,610,952,1020);E('chrome',bound,'InvoiceCalculator / cùng quy tắc tính tiền');show(bound,cue(i,'Lớp tính tiền'));const yy=[800,1090,1380],names=['subtotal()','reduction()','total()'],values=['40.000 + 60.000 → 100.000','100.000 × 10% → 10.000','100.000 − 10.000 → 90.000'],cs=['cộng hàng','tính giảm giá','rồi tính tổng'];yy.forEach((y,j)=>{const n=box(E('trace-strip',g),126,y,830,190);E('small-label',n,names[j]);tx(n,values[j],26,74,780,31,'mono');show(n,cue(i,cs[j]));record(n,cue(i,cs[j]),.5,'model','evaluate '+names[j]);if(j)token(g,j===1?'100.000':'10.000',620,y-94,620,y+55,cue(i,cs[j])-.6,.6);});path(g,'M102 780 V1585 H982 V780',cue(i,3),C.a,'group all operations under one reason to change',.65);}
// 14. Group related code, separate independent sources, then let the rule take the page.
{const i=14,g=scenes[i];title(i,[['Ai cần đổi?\n'],['Vì điều gì?','accent']],64,215,952,115,cue(i,0));const specs=[['subtotal()',C.a,64,775],['reduction()',C.a,420,775],['total()',C.a,745,775],['title',C.v,180,1080],['render()',C.v,620,1080]],nodes=specs.map(([s,col,x,y])=>{const n=box(E('tag',g,s),x,y,0);n.style.width='auto';n.style.color=col;show(n,cue(i,0));return n;});const t=cue(i,1);nodes.slice(0,3).forEach((n,j)=>move(n,{left:100,top:850+j*95},t,.85,'group cohesive calculator operations','model'));nodes.slice(3).forEach((n,j)=>move(n,{left:602,top:920+j*95},cue(i,2),.85,'separate independent presentation operations','model'));const b1=box(E('border-only',g),64,760,450,560),b2=box(E('border-only',g),566,830,450,490);show(b1,t+.3);show(b2,cue(i,2)+.3);tag(i,'CHÍNH SÁCH GIÁ',95,1230,t+.8,C.a);tag(i,'MẪU BẢN IN',600,1230,cue(i,2)+.8,C.v);const rule=tx(g,'Gom cùng lý do.\nTách lý do độc lập.',64,1410,820,58,'display');show(rule,cue(i,2));const sig=tx(g,'S',867,1440,180,190,'display accent');show(sig,cue(i,3));}
// Narration is unchanged for a controlled visual comparison. Captions do not enter the model audit.
P.sections.forEach(s=>{let chunks=[],line=[];for(const w of s.words){if(line.length&&line.map(x=>x.w).join(' ').length+w.w.length>44){chunks.push(line);line=[];}line.push(w);}if(line.length)chunks.push(line);chunks.forEach((ws,i)=>{const n=E('caption-line',document.getElementById('captions'));tl.set(n,{opacity:1},Math.max(s.start,ws[0].t0-.03));tl.set(n,{opacity:0},i+1<chunks.length?chunks[i+1][0].t0-.03:s.start+s.dur-.04);ws.forEach((w,j)=>{if(j)n.appendChild(document.createTextNode(' '));const sp=document.createElement('span');sp.className='caption-word';sp.textContent=w.w;n.appendChild(sp);tl.set(sp,{backgroundColor:'#482C22',color:'#fff'},w.t0);});});});
tl.to(document.getElementById('progress'),{width:780,duration:P.total,ease:'none'},0);window.StoryTimeline=tl;window.__timelines={'noir-story':tl};window.OPERATION_SAMPLES=OPS;window.REVEAL_SAMPLES=REV;
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initSrpStory,{once:true});else initSrpStory();
