function initArchitectStory(){'use strict';
const P=PLAN,S=SCORE,tl=gsap.timeline({paused:true}),OPS=[],REVEALS=[],PLATE_USE=new Set(),root=document.getElementById('persistent');let serial=0;
const C={ink:'#1a1a1a',ivory:'#f4f4f0',blue:'#75bde0',peach:'#f8bc9b',yellow:'#f8d49b',pink:'#f89b9b'};
const norm=s=>String(s).toLowerCase().normalize('NFC').match(/[\p{L}\p{N}]+/gu)||[];
const start=i=>P.sections[i].start,end=i=>start(i)+P.sections[i].dur;
function cue(i,key){if(typeof key==='number')key=S[i].cues[key];const needle=norm(key),words=P.sections[i].words.flatMap(w=>norm(w.w).map(v=>({v,t:w.t0})));if(!words.length){const text=norm(SCRIPT.intro.vo);return start(i)+.5;}const j=words.findIndex((_,j)=>needle.every((v,k)=>words[j+k]?.v===v));if(j<0)throw Error('Missing spoken cue '+i+': '+key);return words[j].t;}
function node(cls,parent=root,text){const n=document.createElement('div');n.className='node '+cls;n.id='n'+(++serial);if(text!=null)n.textContent=text;parent.appendChild(n);return n;}
function box(n,x,y,w,h){Object.assign(n.style,{left:x+'px',top:y+'px',width:w+'px',...(h?{height:h+'px'}:{})});return n;}
function text(g,str,x,y,w,size=36,cls=''){const n=box(node('copy '+cls,g,str),x,y,w);n.style.fontSize=size+'px';return n;}
function rec(n,t,d,kind,job){OPS.push({id:n.id,start:t,end:t+d,kind,job});}
function show(n,t,d=.35,job='disclose native content'){gsap.set(n,{autoAlpha:0,display:'none'});tl.set(n,{display:'block',visibility:'visible'},t);tl.to(n,{opacity:1,duration:d},t);rec(n,t,d,'disclosure',job);REVEALS.push({id:n.id,t});}
function again(n,t){tl.set(n,{display:'block',visibility:'visible',opacity:1},t);}
function hide(n,t,d=.25){tl.to(n,{opacity:0,duration:d},t);tl.set(n,{visibility:'hidden',display:'none'},t+d);}
function move(n,to,t,d=.75,job='recompose reading area',kind='reframe'){tl.to(n,{...to,duration:d,ease:'power2.inOut'},t);rec(n,t,d,kind,job);}
const texts=new Map();function write(n,str,t,job,kind='model'){const before=texts.has(n)?texts.get(n):n.textContent;tl.fromTo(n,{textContent:before},{textContent:str,duration:0,immediateRender:false},t);texts.set(n,str);rec(n,t,.02,kind,job);}
const edit=ArchitectEditorial.create(tl,rec);
const scenes=S.map((s,i)=>{const g=node('shot',document.getElementById('scenes'));tl.set(g,{display:'block',autoAlpha:1},start(i));tl.set(g,{display:'none',autoAlpha:0},end(i));return g;});
S.forEach((s,i)=>{tl.set('#bg',{backgroundColor:({3:C.yellow,6:C.ink,10:C.pink,14:C.blue})[i]||C.ivory},start(i));tl.set('.frame',{borderColor:i===6?C.ivory:C.ink},start(i));});
function title(i,str=S[i].title,size=82,t=start(i)+.1){const n=text(scenes[i],str,88,220,910,size,'heading');if(i===6)n.style.color=C.ivory;show(n,t);return n;}
function label(i,str,x,y,w=900,t=start(i)+.15){const n=text(scenes[i],str,x,y,w,25,'mono');show(n,t);return n;}
function note(i,str,x,y,w,t,size=37,bg='#fff'){const n=box(node('note',scenes[i],str),x,y,w);n.style.fontSize=size+'px';n.style.background=bg;show(n,t);return n;}
function plate(id,x,y,w,h){const n=box(node('plate',document.getElementById('bg')),x,y,w,h),im=document.createElement('img');im.src=PLATES.find(p=>p.id===id).image;im.alt=PLATES.find(p=>p.id===id).alt;n.appendChild(im);n.setAttribute('data-layout-allow-overflow','true');im.id=n.id+'-img';PLATE_USE.add(id);return {n,im};}
function path(i,d,t,col=C.ink,job='draw native causal relation',duration=.7){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('flow');scenes[i].appendChild(svg);const p=document.createElementNS(svg.namespaceURI,'path');p.id='p'+(++serial);p.setAttribute('d',d);p.setAttribute('stroke',col);p.setAttribute('stroke-width',3);p.setAttribute('fill','none');svg.appendChild(p);const len=p.getTotalLength();gsap.set(p,{strokeDasharray:len,strokeDashoffset:len});tl.to(p,{strokeDashoffset:0,duration},t);rec(p,t,duration,'model',job);return p;}
function token(i,str,x,y,xx,yy,t,d=.9,col=C.blue){const n=box(node('token',scenes[i],str),x,y,0);n.style.width='auto';n.style.background=col;show(n,t,.1);move(n,{left:xx,top:yy},t,d,'copy source representation into destination','model');hide(n,t+d,.12);return n;}
function cells(g,x,y,cols=6,rows=3,w=42,h=38,gap=12){return Array.from({length:cols*rows},(_,k)=>box(node('instruction',g),x+(k%cols)*(w+gap),y+Math.floor(k/cols)*(h+gap),w,h));}
function bg(i,color){const n=box(node('',scenes[i]),54,149,972,1500);n.style.background=color;n.style.zIndex=-1;}
const hero=plate('hero',54,149,972,1460),bench=plate('bench',88,555,904,950),cpuArt=plate('cpu',88,530,904,940);
show(hero.n,0,.5);gsap.set([bench.n,cpuArt.n],{autoAlpha:0,display:'none'});
const source=box(node('document'),88,660,900,450);source.id='source-file';const srcHeader=node('doc-top',source,'hello.c');srcHeader.style.position='relative';const code=node('code',source);code.style.position='relative';code.id='source-code';
const lines=['#include <stdio.h>','','int main(void) {','  printf("Chao ban!\\n");','  return 0;','}'];const lineNodes=lines.map((s,i)=>{const n=document.createElement('div');n.className='code-row';n.id='source-line-'+i;n.textContent=s;code.appendChild(n);return n;});
const program=box(node('native-card'),550,780,440,430);program.id='compiled-program';const progLabel=text(program,'hello',0,0,350,58,'heading');progLabel.style.position='relative';const progCells=cells(program,34,155,6,3,42,38,14);const progSub=text(program,'CHƯƠNG TRÌNH',30,338,380,23,'mono');
const compiler=box(node('native-card'),90,750,900,310);compiler.style.background=C.peach;compiler.id='compiler-software';const compTitle=text(compiler,'COMPILER',30,35,840,66,'heading'),compSub=text(compiler,'Trình biên dịch',30,150,830,34);
const output=box(node('terminal'),88,1070,904,310);output.id='run-output';const termTop=node('terminal-top',output,'KẾT QUẢ CHẠY');termTop.style.position='relative';const greeting=text(output,'Chao ban!',30,113,800,76,'mono');greeting.id='greeting';
gsap.set([source,program,compiler,output],{autoAlpha:0,display:'none'});
// 00: image-led opening, native question grounded in the future source/CPU relation.
{let i=0;const h=title(i,'TỪ DÒNG C\nĐẾN CPU.',104);const bar=box(node('band',scenes[i]),90,505,155,17);show(bar,cue(i,0));note(i,'Ai chuyển những dòng chữ\nthành thứ CPU thực hiện được?',88,1350,904,cue(i,2),37);edit.focusWindow({at:cue(i,1),duration:1.1,tracks:[{node:hero.im,from:{scale:1},to:{scale:1.07}}]});}
// 01: the same image yields to a full editable source file.
{let i=1;title(i);edit.plateToExample({at:start(i),duration:.85,tracks:[{node:hero.n,from:{left:54,top:149,width:972,height:1460},to:{left:630,top:1170,width:350,height:430}}]});show(source,cue(i,0));const bracket=box(node('band',scenes[i]),76,747,8,305);show(bracket,cue(i,1));label(i,'VĂN BẢN DO BẠN VIẾT',88,1160,480,cue(i,1));move(lineNodes[3],{backgroundColor:C.yellow},cue(i,2),.45,'identify the one C instruction to inspect','attention');}
// 02: grow the real C line; extract its string as an intended value, not an observed result.
{let i=2;hide(hero.n,start(i));title(i);move(source,{top:600},start(i));const extract=note(i,'"Chao ban!\\n"',160,1280,760,cue(i,1),56,C.yellow);path(i,'M535 874 V1240 M519 1220 L535 1240 L551 1220',cue(i,1),C.ink,'associate string literal with the requested output');label(i,'Ý ĐỊNH · CHƯA PHẢI KẾT QUẢ CHẠY',115,1480,870,cue(i,2));}
// 03: code and CPU require different representations; native mismatch relation.
{let i=3;title(i);move(source,{left:88,top:660,scale:.48},start(i));const cpu=box(node('native-card',scenes[i]),635,675,300,290);cpu.style.background=C.ink;const txt=text(cpu,'CPU',25,75,260,78,'heading');txt.style.color=C.ivory;show(cpu,cue(i,0));const ins=cells(scenes[i],640,1100,5,2,43,36,14);ins.forEach((n,k)=>show(n,cue(i,0)+k*.09,.2));path(i,'M527 810 H595',cue(i,1),C.pink,'identify unsupported direct C-to-CPU route');const cross=text(scenes[i],'×',541,734,100,96,'heading');show(cross,cue(i,1));note(i,'MÃ NGUỒN C ≠ LỆNH MÁY',88,1390,904,cue(i,2),39);label(i,'Ô LỆNH: MINH HỌA',640,1250,350,cue(i,0));}
// 04: insert the software translator into the relation and copy the source into its input.
{let i=4;title(i);move(source,{left:88,top:1130,scale:.46},start(i));show(compiler,Math.max(cue(i,0),start(i)+.8));again(bench.n,start(i));move(bench.n,{left:620,top:1130,width:365,height:395},start(i),.6);token(i,'hello.c',525,1160,620,980,cue(i,1),1);path(i,'M300 1110 V1040',cue(i,1),C.ink,'source is input to compiler software');const translated=note(i,'MÃ CHO MÁY ĐÍCH',88,1430,500,cue(i,2),29,C.yellow);}
// 05: representation transforms in a native strip above the conceptual plate.
{let i=5;hide(source,start(i));hide(compiler,start(i));title(i,undefined,70);move(bench.n,{left:88,top:700,width:904,height:880},start(i),.8);const strip=box(node('native-card',scenes[i]),88,500,904,166);strip.style.background=C.blue;const a=text(strip,'IN LỜI CHÀO',25,43,750,48,'heading');show(strip,cue(i,0));const pieces=cells(scenes[i],138,557,12,1,48,54,18);pieces.forEach((n,k)=>{show(n,cue(i,2)+k*.04,.12);n.style.background=C.yellow;});hide(a,cue(i,2));move(strip,{backgroundColor:'#fff'},cue(i,2),.7,'transform native source representation into symbolic instruction representation','model');label(i,'Ý ĐỊNH GIỮ NGUYÊN',88,1475,790,cue(i,1));}
// 06: explicitly collapse the physical analogy into the actual software object.
{let i=6;title(i);note(i,'HÌNH MINH HỌA / KHÔNG PHẢI THIẾT BỊ',88,465,904,cue(i,0),25,C.yellow);edit.plateToExample({at:cue(i,1),duration:.9,tracks:[{node:bench.n,from:{left:88,top:700,width:904,height:880},to:{left:88,top:740,width:420,height:610}}]});again(compiler,cue(i,1));move(compiler,{left:555,top:780,width:435,height:310},cue(i,1),.8);move(compTitle,{fontSize:47,width:380},cue(i,1),.8);move(compSub,{fontSize:30,width:360},cue(i,1),.8);write(compTitle,'CLANG',cue(i,2),'name the concrete compiler software','disclosure');note(i,'Một chương trình\nchạy trên máy bạn.',555,1160,435,cue(i,2),34);}
// 07: invoke real checked command; read source without deleting it. Native read sweeps feed translation.
{let i=7;hide(bench.n,start(i));hide(compiler,start(i));title(i,undefined,79);again(source,start(i));move(source,{left:88,top:600,scale:1},start(i),.6);const cmd=box(node('terminal',scenes[i]),88,1120,904,185);const c=node('terminal-line',cmd,'$ clang hello.c -o hello');c.style.position='relative';show(cmd,cue(i,0));const scan=box(node('',scenes[i]),116,700,826,7);scan.style.background=C.peach;show(scan,cue(i,1),.1);move(scan,{top:985},cue(i,1),1.9,'compiler reads the input source','model');token(i,'hello.c',790,1000,790,1200,cue(i,1),1.3);note(i,'Sơ đồ gom các bước tạo chương trình.',88,1410,904,cue(i,2),32);}
// 08: copy vs consume: source stays; distinct output materializes from transformed representation.
{let i=8;title(i);move(source,{left:88,top:660,scale:.46},start(i),.7);label(i,'BẢN NGUỒN GIỮ NGUYÊN',88,925,460,cue(i,0));const editable=note(i,'ĐỌC / SỬA',88,1080,414,cue(i,1),43,C.blue);show(program,cue(i,2)+.8);rec(program,cue(i,2)+.8,.2,'model','commit a distinct executable artifact while source remains');gsap.set(progCells,{autoAlpha:0});token(i,'đầu ra',242,965,624,960,cue(i,2),.8,C.peach);path(i,'M310 982 H716',cue(i,2),C.ink,'source retained alongside a separately created output artifact',.8);label(i,'HAI TỆP RIÊNG',300,1420,600,cue(i,2)+.8);}
// 09: reveal executable contents and explicitly withhold greeting until run.
{let i=9;title(i,undefined,75);move(source,{left:88,top:1240,scale:.40},start(i));move(program,{left:88,top:570,width:904,height:520},start(i),.75);move(progLabel,{fontSize:76},start(i),.75);move(progSub,{top:425,width:840},start(i),.75);progCells.forEach((n,k)=>{tl.set(n,{left:35+(k%9)*91,top:178+Math.floor(k/9)*90,width:70,height:60},start(i));show(n,cue(i,1)+k*.06,.2);});rec(program,cue(i,1),1.25,'model','populate executable with symbolic instruction contents');const extra=text(program,'+ dữ liệu và các phần cần thiết',32,360,820,28);show(extra,cue(i,1)+.9);note(i,'ĐÃ TẠO TỆP. CHƯA CHẠY.',88,1140,904,cue(i,2),40,C.yellow);label(i,'hello.c vẫn còn',505,1370,430,cue(i,2));}
// 10: expand symbolic cells; reject one-to-one mapping using actual grouping.
{let i=10;title(i);hide(source,start(i));hide(program,start(i));const group=box(node('native-card',scenes[i]),88,620,904,565);group.style.background='#fff';show(group,cue(i,0));const ins=cells(group,45,70,6,3,115,72,21);ins.forEach((n,k)=>show(n,cue(i,0)+k*.04,.15));label(i,'CÁC Ô TƯỢNG TRƯNG · KHÔNG PHẢI BIT THẬT',118,1110,844,cue(i,0));const line=note(i,'Một dòng C',88,1270,315,cue(i,1),37,C.blue);const multi=note(i,'Nhiều lệnh máy',568,1270,424,cue(i,1)+.5,37,C.yellow);path(i,'M421 1340 H543 M525 1323 L543 1340 L525 1357',cue(i,1),C.ink,'one C statement can map to multiple machine instructions');ins.forEach((n,k)=>{if(k<6)move(n,{backgroundColor:C.yellow},cue(i,2)+k*.08,.35,'identify CPU-executable instruction group','attention');});}
// 11: launch artifact, OS loads it, native CPU instruction sequence starts.
{let i=11;title(i);again(cpuArt.n,start(i));move(cpuArt.n,{left:570,top:790,width:420,height:700},start(i),.1);const launch=box(node('terminal',scenes[i]),88,530,904,170);const l=node('terminal-line',launch,'$ ./hello');l.style.position='relative';show(launch,cue(i,0));again(program,start(i));move(program,{left:88,top:800,scale:.45},start(i),.5);const os=note(i,'HỆ ĐIỀU HÀNH',88,1180,410,cue(i,1),30,C.peach);os.style.height='220px';token(i,'hello',220,740,220,1300,cue(i,1),.8,C.yellow);path(i,'M495 1250 H630',cue(i,2),C.ink,'OS starts program execution on CPU');token(i,'lệnh máy',220,1300,680,1260,cue(i,2),1,C.blue);label(i,'CPU / THỰC THI',560,1530,430,cue(i,2));}
// 12: actual observable output commits after library/OS path, never directly from compiler.
{let i=12;title(i);hide(program,start(i));edit.focusWindow({at:start(i),duration:.8,tracks:[{node:cpuArt.n,from:{left:570,top:790,width:420,height:700},to:{left:88,top:530,width:430,height:470}},{node:cpuArt.im,from:{scale:1},to:{scale:1.15}}]});const library=note(i,'THƯ VIỆN\n+ HỆ ĐIỀU HÀNH',565,600,425,cue(i,0),33,C.peach);path(i,'M517 760 H555',cue(i,0),C.ink,'program calls output functions');show(output,cue(i,1));gsap.set(greeting,{autoAlpha:0});token(i,'Chao ban!',670,860,540,1150,cue(i,1)-.75,.75,C.yellow);show(greeting,cue(i,1),.2,'commit visible stdout');rec(greeting,cue(i,1),.2,'model','program stdout receives Chao ban newline');note(i,'KẾT QUẢ CỦA CHƯƠNG TRÌNH',88,1470,904,cue(i,2),28);}
// 13: grow committed output then open same source beside it for verification.
{let i=13;hide(cpuArt.n,start(i));title(i);edit.resultToEvidence({at:cue(i,0),duration:.85,tracks:[{node:output,from:{left:88,top:1070,width:904,height:310},to:{left:88,top:1150,width:904,height:300}}]});tl.set(source,{left:88,top:565,scale:1},start(i));again(source,cue(i,0));path(i,'M810 840 H1010 V1310 H935',cue(i,1),C.ink,'compare source string literal with observed stdout');const same=note(i,'CÙNG MỘT LỜI CHÀO',88,1030,904,cue(i,1),35,C.yellow);label(i,'NỘI DUNG DO MÃ NGUỒN QUY ĐỊNH',88,1520,910,cue(i,2));}
// 14: distinguish creation output from runtime output using the two actual artifacts.
{let i=14;hide(source,start(i),0);title(i);again(program,start(i));move(program,{left:88,top:680,scale:.44},start(i),.7);move(output,{left:88,top:1270,width:904,height:300},start(i),.7);label(i,'01 / BIÊN DỊCH',88,540,904,cue(i,1));note(i,'Tạo tệp\nchương trình',550,670,440,cue(i,1),48,C.yellow);label(i,'02 / CHẠY',88,1130,904,cue(i,2));path(i,'M300 920 V1205 H535',cue(i,2),C.ink,'running created executable produces the separate stdout result');}
// 15: reconstruct the causal chain, keep source's authorship explicit.
{let i=15;hide(program,start(i));hide(output,start(i));title(i,'COMPILER\nCHUYỂN BIỂU DIỄN.',78);const labels=['MÃ NGUỒN C','COMPILER','MÃ MÁY','CPU THỰC THI'],ys=[620,825,1030,1235],colors=[C.blue,C.peach,C.yellow,C.ink];labels.forEach((s,k)=>{const n=note(i,s,175,ys[k],730,cue(i,k),43,colors[k]);if(k===3)n.style.color=C.ivory;if(k)path(i,`M540 ${ys[k]-77} V${ys[k]-16} M524 ${ys[k]-32} L540 ${ys[k]-16} L556 ${ys[k]-32}`,cue(i,k),C.ink,'connect ordered source-to-execution stage');});label(i,'BẠN VIẾT Ý ĐỊNH. MÁY THỰC THI.',100,1515,910,cue(i,4));}
// Karaoke is independent of model operations; word times are estimated or ASR-refined.
P.sections.forEach((s,i)=>{const badge=node('mono',document.getElementById('page'),String(i+1).padStart(2,'0')+'/16');badge.style.position='absolute';badge.style.right=0;show(badge,s.start,.01);hide(badge,s.start+s.dur-.02,.01);let chunks=[],line=[];for(const w of s.words){if(line.length&&line.map(x=>x.w).join(' ').length+w.w.length>47){chunks.push(line);line=[];}line.push(w);}if(line.length)chunks.push(line);chunks.forEach((ws,j)=>{const n=node('caption-line',document.getElementById('captions'));tl.set(n,{opacity:1},Math.max(s.start,ws[0].t0-.02));tl.set(n,{opacity:0},j+1<chunks.length?chunks[j+1][0].t0-.02:s.start+s.dur-.03);ws.forEach((w,k)=>{if(k)n.appendChild(document.createTextNode(' '));const span=document.createElement('span');span.className='caption-word';span.textContent=w.w;n.appendChild(span);tl.set(span,{backgroundColor:C.yellow},w.t0);});});});
tl.to('#progress',{width:770,duration:P.total,ease:'none'},0);
window.StoryTimeline=tl;window.__timelines={'architect-story':tl};window.OPERATION_SAMPLES=OPS;window.REVEAL_SAMPLES=REVEALS;window.PLATE_USAGE=[...PLATE_USE];
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initArchitectStory,{once:true});else initArchitectStory();
