/* Cache example only: an explicit synchronous key A -> 42 model. Author new choreography for other topics. */
function buildCutout(){const B=Cutout,D=CutoutDesign,tl=gsap.timeline({paused:true}),P=PLAN,S=SCRIPT,root=document.getElementById('pages'),caps=document.getElementById('captions'),checks=[],pages=[];
if(S.scenes.length!==2||S.language!=='vi')throw Error('Starter is the Vietnamese two-request cache example; adapt model and visual copy for another script/language.');
[S.intro,...S.scenes,S.outro].forEach((c,i)=>{const p=P.sections[i],page=B.node('article','page',root);page.dataset.section=p.id;pages.push(page);gsap.set(page,{display:i===0?'block':'none',x:0});
if(i===0){D.hook(page);const hand=page.querySelector('img');B.appear(tl,hand,p.start+.1,.4);tl.fromTo(hand,{y:70},{y:0,duration:.65,ease:'power2.out',immediateRender:false},p.start+.1);}
else if(i===1||i===2){D.top(page,c.title,i===1?'CACHE / LẦN HỎI ĐẦU':'CACHE / LẦN HỎI TIẾP');page.querySelector('.meta').textContent=i===1?'CACHE / LẦN HỎI ĐẦU':'CACHE / LẦN HỎI TIẾP';const v=D.scene(page,{cached:i===2,calls:i===2?1:0});const request=B.cue(c,p,'request'),reply=B.cue(c,p,'reply');
 v.response.textContent='Yêu cầu A';
 const responseReady=D.box(page,'answer',76,1360,928,102,'Kết quả A → 42');gsap.set(responseReady,{autoAlpha:0});
 if(i===1){const fetched=request+.42,stored=B.cue(c,p,'cache')+.45;if(!(fetched<stored&&stored<reply+.3))throw Error('Revise cues to preserve fetch -> store -> reply.');const calls=D.text(page,'counter','1',698,1170,294);calls.dataset.calls='';gsap.set(calls,{autoAlpha:0});tl.set(v.count,{autoAlpha:0},fetched);tl.set(calls,{autoAlpha:1},fetched);
 const proxy=D.box(page,'native-token',0,0,148,114,'42');proxy.dataset.proxy='';proxy.dataset.layoutAllowOverlap='';proxy.dataset.layoutAllowOcclusion='';B.appear(tl,proxy,B.cue(c,p,'cache'),.08);B.move(tl,proxy,[757,907],[301,924],B.cue(c,p,'cache'),.45,'cache store');const val=D.text(v.cache,'num','42',168,21,215);val.dataset.cache='';gsap.set(val,{autoAlpha:0});tl.set([proxy,v.cachedValue],{autoAlpha:0},stored);tl.set(val,{autoAlpha:1},stored);checks.push({kind:'store',start:B.cue(c,p,'cache'),commit:stored,fetched,reply,section:p.id});
 }else{const hit=B.cue(c,p,'hit');tl.fromTo(v.cache,{scale:1},{scale:1.035,duration:.2,repeat:1,yoyo:true,immediateRender:false},hit);const proxy=D.box(page,'native-token',0,0,148,114,'42');proxy.dataset.proxy='';proxy.dataset.layoutAllowOverlap='';proxy.dataset.layoutAllowOcclusion='';B.appear(tl,proxy,reply,.08);B.move(tl,proxy,[280,926],[400,1347],reply,.5,'cache hit reply');tl.set(proxy,{autoAlpha:0},reply+.5);checks.push({kind:'hit',start:reply,commit:reply+.5,section:p.id});}
 const commit=i===1?reply+.25:reply+.5;tl.set(v.response,{autoAlpha:0},commit);tl.set(responseReady,{autoAlpha:1},commit);D.text(page,'footer',i===1?'Nguồn vẫn giữ dữ liệu. Cache nhận một bản.':'Cùng key A → dùng lại 42, lượt gọi nguồn vẫn là 1.',76,1510,928);
}else{D.top(page,c.title,'CACHE / GHI NHỚ');D.plane(page,'#dafc63',66,720,912,710,-3);D.img(page,'hand-card',270,700,710,-7);const rule=D.box(page,'slip',76,1290,930,158,'Dùng lại kết quả.\nCần kiểm soát độ mới.');rule.style.whiteSpace='pre-line';}
B.captions(tl,p,caps);});pages.slice(1).forEach((page,j)=>{const duration=Math.min(.65,P.sections[j].dur*.15),end=P.sections[j+1].start;CutoutChoreography.push(tl,pages[j],page,{start:end-duration,duration});});tl.set(pages.at(-1),{display:'none'},P.total);tl.set({}, {},P.total);window.__timelines={'cutout-programming':tl};window.CUTOUT_CHECKS=checks;
}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildCutout,{once:true});else buildCutout();
